### ISSUE TITLE
Endpoint response not showing in swagger definition

### ISSUE THREAD

**Issue by gottfrois** [rswag/rswag#1]
Thanks for the great work! This thing is amazing.

Please correct me if i'm wrong but the endpoint response is not currently saved in the swagger definition file right?

``` ruby
get 'Retreive endpoint specified by id' do
  consumes 'application/vnd.api+json'
  produces 'application/vnd.api+json'
  parameter :id, in: :path, type: :string, required: true, description: "The endpoint id"

  response '200', 'success' do
    let(:endpoint) { Endpoint.create! }
    let(:id) { endpoint.id }

    run_test!
  end
end
```

produces

``` json
"paths": {
  "/api/v1/endpoints/{id}": {
    "get": {
      "tags": [
        "Endpoints API"
      ],
      "summary": "Retreive endpoint specified by id",
      "consumes": [
        "application/vnd.api+json"
      ],
      "produces": [
        "application/vnd.api+json"
      ],
      "parameters": [
        {
          "name": "id",
          "in": "path",
          "type": "string",
          "required": true,
          "description": "The endpoint id"
        }
      ],
      "responses": {
        "200": {
          "description": "success"
        }
      }
    }
  }
}
```

Any chance to save the response payload as well? Thanks

**Comment by domaindrivendev** [comment]
Will be building that in as well as the remaining Swagger attributes that aren't currently supported as soon as I get a chance. Hopefully within the next 2 weeks. Stay tuned!

**Comment by gottfrois** [comment]
Damn, now I'm excited! :) Thanks man

**Comment by SarSar440** [comment]
Good Stuff! I will look forward to seeing the other attributes added soon too.

**Comment by drewish** [comment]
I also had the same need. Over on https://github.com/domaindrivendev/swagger_rails/pull/20 I've got it capturing the response and including it in the examples.

**Comment by drewish** [comment]
That other PR got closed but I've incorporated it into my gem: https://github.com/drewish/rspec-rails-swagger

**Comment by domaindrivendev** [comment]
@gottfrois, @SarSar440. Check out the latest version 1.0.0 as it has this and lots of other great features added. NOTE: the name change from swagger_rails to rswag. Also worth noting there's a minor breaking change - the "parameter" method in the rspec DSL now expects a single argument (attributes) that includes "name" instead of two arguments (name, attributes).

Check out the readme example for specifying an expected response schema. This will document it in the UI and also test your response against the schema when you run the tests
