### ISSUE TITLE
Support for multiple "top level" params

### ISSUE THREAD

**Issue by erlandsona** [rswag/rswag#102]
Rswag is currently setup to grab the first top level param specified. https://github.com/domaindrivendev/rswag/blob/master/rswag-specs/lib/rswag/specs/request_factory.rb#L153

It would be nice to be able to define something like so...
```
post 'Create a new Thing' do
  tags 'Things'
  consumes 'application/json'
  produces 'application/json'
  parameter name: :name, in: :body, required: true, type: :string
  parameter name: :other_ids, in: :body, required: true, schema: {
    type: :array, items: {type: integer, format: :int64} 
  }

response 201, :created do
  let(:name) { "Fake Name" }
  let(:other_ids) { [1,2,3] }
  # this would do something like `post :create, params: {name: "Fake Name", other_ids: [1,2,3]}`
  run_test!
end
```

```
    post 'Create a new Thing' do
      tags 'Things'
      consumes 'application/json'
      produces 'application/json'
      # From https://swagger.io/docs/specification/2-0/describing-request-body/
      # The payload name. It is required but ignored (it is used for documentation purposes only).
      parameter name: :params, in: :body, required: true, schema: {
        type: :object,
        required: [:other_ids, :name],
        properties: {
          other_ids: {
            type: :array,
            items: {
              type: :integer,
              format: :int64
            }
          },
          name: { type: :string }
        }
      }


      response 201, :created do
        let(:params) { Hash[name: "Fake Name", other_ids: [1,2,3]] }
        run_test!
      end
```

Thank you for making this Gem as this issue forced me to dig into the swagger spec and find that bit about the payload name being ignored. 
Helped make the current implementation make a lot more sense.

**Comment by domaindrivendev** [comment]
As per the [Swagger spec](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#parameterObject), specifically where it discusses the different parameter types:

_"Body - The payload that's appended to the HTTP request. Since there can only be one payload, there can only be one body parameter. The name of the body parameter has no effect on the parameter itself and is used for documentation purposes only. Since Form parameters are also in the payload, body and form parameters cannot exist together for the same operation."_

You can only specify a one "body" parameter and that's why the rswag implementation only cares about the first. A second would be invalid

**Comment by erlandsona** [comment]
Hey thanks for the response! And that makes perfect sense. It just took a little more digging into the swagger spec to figure out why that was the case.
