### ISSUE TITLE
Cannot explicitly require rswag.

### ISSUE THREAD

**Issue by kelishrestha** [rswag/rswag#108]
I was having dependency issue with deployment using rswag([Exact Issue](https://github.com/domaindrivendev/rswag/issues/77)), which I solved by setting `require: false` in the gemfile. 

However, now I cannot require rswag into the initializers with `require 'rswag'` or with any of its dependencies like 

```
require 'rswag/specs'
require 'rswag/api'
require 'rswag/ui'
``` 

Is there any way to lazy load the gem?

**Comment by Kutomore** [comment]
I don't know if it would fix your issue, and you probably don't even have that issue anymore, but I'm gonna answer here in case someone stumbles upon this with an similar issue. The way I usually load my dependencies when I have rspec is including them on the root file `.rspec` kinda like this:

```
--require spec_helper
--require rails_helper
--require swagger_helper
```

It might not be the best way to do it since I'm always loading all dependencies even if I don't need them, but in projects with massive amounts of testing it still didn't give me any trouble.
