### ISSUE TITLE
Custom "Integration" Spec Location

### ISSUE THREAD

**Issue by douglasrlee** [rswag/rswag#118]
It would be nice if we could specify a custom location for these swagger tests. The /spec/integrations location clashes with out existing integration tests.

**Comment by domaindrivendev** [comment]
Rswag-specs is built on top of [rspec-rails "request-specs"](https://github.com/rspec/rspec-rails#request-specs). In fact, the `rswag:specs:swaggerize` rake task is really just a convenient wrapper around the following command:

```
rspec --pattern spec/requests/**/*_spec.rb, spec/api/**/*_spec.rb, spec/integration/**/*_spec.rb --format Rswag::Specs::SwaggerFormatter --dry-run --order defined
```

As you can see, the above command looks in any one of the following locations - "requests", "api", "integrations" and that's because they're the same locations that `rspec-rails` uses by default to distinguish between "request specs" and other spec types.

So, if you want to isolate the `rswag` request specs from your existing integration tests, then I would suggest putting them into the "api" folder. Then, instead of running `rswag:specs:swaggerize` to generate your Swagger.json files, just run the following:

```
rspec --pattern spec/api/**/*_spec.rb --format Rswag::Specs::SwaggerFormatter --dry-run --order defined
```

**Comment by domaindrivendev** [comment]
Of course this could all be abstracted away into a single config setting to simplify your use case - but that will require a bit more digging to make sure it still ties in with `rspec-rails` correctly. So, more work than I can take on right now. But, PR's are always welcome 😉

**Comment by bbascarevic** [comment]
To anyone needing this, it appears that in the current version you can set the env variable `PATTERN`, for example `PATTERN="spec/openapi/**/*_spec.rb" rails rswag`
