### ISSUE TITLE
Detailed description

### ISSUE THREAD

**Issue by arthursoas** [rswag/rswag#158]
Thanks for the gem!
Is there any way to put some detailed description on my method?

For example, on my API the user has to insert a 'format_code', but would be great if I could show which options he/she have, like:
1: square
2: triangle
3: circle

It's just a textual information, not necessarily a formatted list.

Thanks.

**Comment by jasjeet30** [comment]
I'm also looking for this.
Like the description of the param.

**Comment by jpastika** [comment]
Looking for the same.  I want to be able to add a detailed description to my endpoint.  I see that I can include a "description" attribute, but I do not see a way to format.  I tried using markdown as suggested here: https://github.com/rswag/rswag#formatting-the-description-literals, but it does not seem to work.

**Comment by jtannas** [comment]
Heyo - I'm new and sorting through our issue backlog then came across this.
Does swagger's [`enum`](https://swagger.io/docs/specification/data-models/enums/) or [`String pattern`](https://swagger.io/docs/specification/data-models/data-types/#string) fit what you're looking for?

**Comment by jtannas** [comment]
I've added this to our examples section. https://github.com/rswag/rswag/wiki/Examples#documenting-a-query-parameter-with-a-list-of-allowed-values

Since this is a very old thread I'm going to close it now, but please feel free to make a new issue if you're still running into problems. Cheers! :slightly_smiling_face:
