### ISSUE TITLE
using rswag with acts_as_tenant

### ISSUE THREAD

**Issue by ahmadabdelhalim** [rswag/rswag#162]
I'm trying to use rswag with acts_as_tenant, I wanna add the tenant to the path file in order to make the path work, but I don't know how can I achieve that.

**Comment by jaydorsey** [comment]
Is the tenant in your path, or is it in the host (domain/subdomain?)

**Comment by ahmadabdelhalim** [comment]
@jaydorsey 
It's in the subdomain.

**Comment by jaydorsey** [comment]
The swagger documentation has some information on [multiple hosts](https://swagger.io/docs/specification/2-0/api-host-and-base-path/) in the FAQ near the bottom.

> Multiple hosts are supported in OpenAPI 3.0. 2.0 supports only one host per API specification (or two if you count HTTP and HTTPS as different hosts). A possible way to target multiple hosts is to omit the host and schema from your specification and serve it from each host. In this case, each copy of the specification will target the corresponding host.

Since this gem is targeting 2.0 (per the README), until 3.0 support is available, it doesn't sound like this will be available. In order to get your specs to work, you may need to stub out the domain/base host in your specs. If you can provide some more info on what you mean by "make the path work" I might be able to provide some suggestions. Do you mean to get the specs to pass, to use the try-it-out feature, does it fail with generating documentation, etc.

We're using acts_as_tenant now, but we aren't using a host-based scheme for differentiating tenants.

Off the top of my head:

You might be able to setup an alias in your rails configuration so foo.bar.com/ and bar.com/foo/ are aliased/equivalent. This would let you use a regular old path parameter in your documentation (but that might get confusing in the long run)

**Comment by ahmadabdelhalim** [comment]
@jaydorsey 
Basically, I just want to add the subdomain to the path so rswag can run it correctly. For example: `foo.bar.com/`

**Comment by jaydorsey** [comment]
@ahmadabdelhalim have you tried setting the `host` in your swagger_helper.rb file?

The host and basePath should be all that you need to change. This would show up in the generated docs, and you'd work with a fixed-host (whatever you specified) when you where using the "Try it out" feature I think

https://swagger.io/docs/specification/2-0/api-host-and-base-path/

**Comment by jtannas** [comment]
I'm going to close this issue now since the original poster never responded to the last question.
If you're running into a similar problem feel free to open a new issue and I'll be happy to help :slightly_smiling_face: 
Cheers!
