### ISSUE TITLE
More examples (session login, devise) and "normal" object

### ISSUE THREAD

**Issue by Strnadj** [rswag/rswag#175]
1) Our API is based on session authentication, we have factories for everything but I was not able to use them or use Devise helper (https://github.com/plataformatec/devise/wiki/How-To:-sign-in-and-out-a-user-in-Request-type-specs-(specs-tagged-with-type:-:request))

because of:

```
Failure/Error: sign_in(create(:admin_user))
  `create` is not available on an example group (e.g. a `describe` or `context` block). It is only available from within individual examples (e.g. `it` blocks) or from constructs that run in the scope of an example (e.g. `before`, `let`, etc).)
```

2) "normal object" - I am not sure how provided example with `blog` can actually work with Rails REST. I copy that:

```
require 'swagger_helper'

describe 'Sessions API', type: :request do

  path '/api/users/sign_in' do

    post 'Sign in user' do
      tags 'Session'
      consumes 'application/json'

      parameter name: :user, in: :body, schema: {
        type: :object,
        properties: {
          login: { type: :string },
          password: { type: :string }
        },
        required: [ 'login', 'password' ]
      }

      response '201', 'User signed' do
        let(:user) { { login: 'admin', password: 'Password123456' } }
        run_test!
      end
    end
  end
end
```

but when I try that in swagger UI it sends `{ login: '..', password: '...' }` not `{  user: { login: ..., password:  ... } }` as expected.

And at the end of the day... it seems like "params" in URL does not work at all:

http://prntscr.com/lw77f4

Thank for the response.

**Comment by ConorSheehan1** [comment]
+1, similar to https://github.com/domaindrivendev/rswag/issues/132

> when I try that in swagger UI it sends { login: '..', password: '...' } not { user: { login: ..., password: ... } } as expected.

I found a workaround, but it's hacky https://github.com/domaindrivendev/rswag/issues/132#issuecomment-440655285
```ruby
let(:user) { { user: { login: 'admin', password: 'Password123456' } } }
```

> it seems like "params" in URL does not work at all

I think query params do work as expected. You're sending the user param in the post body.
Changing `in: :body` to in: :query` could solve your problem if your app does accept authentication details in url params.

I think the confusion is that `let` will add a key and value to the url using `in: query`, but `in: body` only adds a value. I don't think this can be changed though because a url param will always be a key value pair, while a post body could be many different structures, for example an array which then contains key value pairs.

**Comment by BookOfGreg** [comment]
Closing as I believe Conor solved the issue.
