### ISSUE TITLE
Request factory jsonifies body params even if consumes "text/plain"

### ISSUE THREAD

**Issue by sfenig** [rswag/rswag#181]
https://github.com/domaindrivendev/rswag/blob/5ea1670d79b93d363b0f4a735da92e29a0aa1efd/rswag-specs/lib/rswag/specs/request_factory.rb#L153

1) set consumes to text plain,
2) set body parameter (in: body) to string
3) make it a string with newlines and doublequotes (things escaped by to_json)
3) view request.body.read in controller action
4) see that they get escaped, they shouldn't

**Comment by sfenig** [comment]
Not a dry solution, but this solves the problem:

```
module Rswag
  module Specs
    class RequestFactory
      def add_payload(request, parameters, example)
        content_type = request[:headers]['CONTENT_TYPE']
        return if content_type.nil?

        if [ 'application/x-www-form-urlencoded', 'multipart/form-data' ].include?(content_type)
          request[:payload] = build_form_payload(parameters, example)
        elsif content_type == 'application/json'
          request[:payload] = build_json_payload(parameters, example)
        else
          request[:payload] = build_plain_payload(parameters, example)
        end
      end

      def build_plain_payload(parameters, example)
        body_param = parameters.select { |p| p[:in] == :body }.first
        body_param ? example.send(body_param[:name]) : nil
      end
    end
  end
end

```

**Comment by BookOfGreg** [comment]
This sounds like a bug to me, I haven't validated it locally yet but would you (or future readers) like to submit a PR with a test on this topic?

**Comment by lucasmenezesds** [comment]
@BookOfGreg How can I help with that?

Because I'm facing the same problem.

IMO this is where it begins:
https://github.com/rswag/rswag/blob/5ea1670d79b93d363b0f4a735da92e29a0aa1efd/rswag-specs/lib/rswag/specs/request_factory.rb#L133

Since there's no `raw` option and there's only 2 options to convert the data (making a Hash or transforming it to JSON), when the data is sent, it's converting to the string "again" so,  `"Expected String"` **becomes** `"\"Expected String\""`.

So how can I help? I mean, what exactly you would like me to do on the PR? I should work on the [test-app](https://github.com/rswag/rswag/tree/master/test-app), right!?

**Comment by islador** [comment]
Just hit this during some development as a new rswag user. Definitely still present and definitely breaking when you need to pass in a string to emulate someone else's API.

**Comment by Ksm125** [comment]
> This sounds like a bug to me, I haven't validated it locally yet but would you (or future readers) like to submit a PR with a test on this topic?

@BookOfGreg i opened a PR regarding this bug, if you could have a look :)
