### ISSUE TITLE
Required: false doesn't work for parameter

### ISSUE THREAD

**Issue by arianf** [rswag/rswag#182]
When I am using parameters, `required: false` doesn't work.

```ruby
parameter name: :filter_for, in: :path, type: :string, required: false, description: 'test'
```

generates

```json
        "parameters": [
          {
            "name": "filter_for",
            "in": "path",
            "type": "string",
            "required": true,
            "description": "test"
          }
        ],
```

I've also tried `required: 'false'`

**Comment by arianf** [comment]
Here is the problem

https://github.com/domaindrivendev/rswag/blob/a50bf616b95564788ebed79b6bd577a2f7f10114/rswag-specs/lib/rswag/specs/example_group_helpers.rb#L39-L41

Why are we forcing `:required` = `true` for all paths?!? This is weird... why isn't this:

```ruby
if attributes[:in] && attributes[:in].to_sym == :path && attributes[:required].nil?
   attributes[:required] = true
end
```

**Comment by jaydorsey** [comment]
I'd expect a `:path` field to be required, otherwise it wouldn't be the same path you're testing...

Can you post the path you're using for this? With the example above, I'd expect you to use `in: :query` rather than `in: :path`, for a non-required field. I just wanted to see the example mostly so I can compare it against the way I'm structuring my documentation.

Update: 

For example, with `path '/foo/{filter_for}`, if you don't include that attribute, what distinguishes it from another `path '/foo` (except maybe the trailing slash)

**Comment by arianf** [comment]
Ohhh, I've been using path instead of query. oops. Closing, sorry.
