### ISSUE TITLE
Unable to validate json:api schema

### ISSUE THREAD

**Issue by heaven** [rswag/rswag#198]
It would be great to at least have an ability to disable schema validation.

**Comment by jaydorsey** [comment]
@heaven can you provide some more context and clarify your comment? 

I'm also using jsonapi and I have schema validation working. The title says "unable to validate" but the body of your request implies you want to disable it so it isn't clear if it's broken or not.

**Comment by heaven** [comment]
@jaydorsey, hi, sure. For an unknown reason, the validation started failing with the `Unable to validate schema` error right after I switched to JSON API. So I thought this format is not supported and was looking at how to disable the validation (and disabled eventually).

Do I need anything special for JSON API data format to work? Should I define the schema in a special way or so? I will be testing this more tomorrow.

**Comment by jaydorsey** [comment]
You shouldn't need to do anything special to define the schema as far as I know. 

I've been using [parrish/json-schema_builder](https://github.com/parrish/json-schema_builder) gem to wrap building my request schemas and it's worked out just fine. If you can provide a sample schema and a snippet of your spec that shows how/where you used it I might be able to see why the error is caused or give you a pointer.

For response schemas, we're just validating against this [eneuhauser/json-api](https://github.com/eneuhauser/json-api/blob/schema/schema) schema with a very slight modification (I had to escape some quotes IIRC) using the [thoughtbot/json_matchers](https://github.com/thoughtbot/json_matchers) gem.

Our response tests look like this at a bare minimum:

    run_test! do
      expect(json_response).to match_json_schema('response')
    end

We typically have additional assertions, but that's always our starting point

**Comment by heaven** [comment]
I didn't add any custom assertions, but simply calling the `run_test!`, which already does this:

```ruby
assert_response_matches_metadata(example.metadata, &block)
```

Here's the parsed response body:

```ruby
{"data"=>
  [{"id"=>"5",
    "type"=>"member",
    "attributes"=>
     {"email"=>"felicitas@schroederpollich.net",
      "first_name"=>"Zachariah",
      "last_name"=>"Cormier"}},
   {"id"=>"4",
    "type"=>"member",
    "attributes"=>
     {"email"=>"lasonyarogahn@baumbach.com",
      "first_name"=>"Sammy",
      "last_name"=>"Hoppe"}},
   {"id"=>"3",
    "type"=>"member",
    "attributes"=>
     {"email"=>"james@legrosrowe.info",
      "first_name"=>"Malika",
      "last_name"=>"Blanda"}}],
```

Our `member` model schema definition:

```ruby
member: {
  type:       :object,
  properties: {
    first_name: { type: :string },
    last_name:  { type: :string },
    email:      { type: :string }
  },
  required:   ['email']
}
```

And the spec:

```ruby
require 'swagger_helper'

describe 'Members API', swagger_doc: 'carmen/v1/swagger.json' do
  let(:members) { 3.times.map { FactoryBot.create(:member) } }

  path '/members/recent' do
    get 'Retrieves member profile details' do
      tags 'Members'
      security [apiKey: []]
      parameter name: "page[number]", in: :query, type: :integer, required: false
      parameter name: "page[size]", in: :query, type: :integer, required: false

      response '200', 'Ok' do
        schema type: :array, items: { '$ref' => '#/definitions/member' }

        before do
          members.first.update_column(:created_at, 3.minutes.ago)
          members.second.update_column(:created_at, 2.minutes.ago)
        end

        run_test! do |response|
          expect(JSON.parse(response.body)["data"].map { |d| d["id"].to_i }).to eq members.map(&:id).reverse
        end
      end
    end
  end
end
```

The spec passes if I comment out the `schema type: :array` string, and fails with the following error otherwise:

```
  1) Members API /members/recent get Ok returns a 200 response
     Failure/Error: VCR.turned_off { example.run }

     Rswag::Specs::UnexpectedResponse:
       Expected response body to match schema: The property '#/' of type object did not match the following type: array in schema 23ae0549-e98d-5925-928e-8227859224d4
     # /Users/heaven/.rvm/gems/ruby-2.4.1@crm/gems/rswag-specs-2.0.5/lib/rswag/specs/response_validator.rb:46:in `validate_body!'
     # /Users/heaven/.rvm/gems/ruby-2.4.1@crm/gems/rswag-specs-2.0.5/lib/rswag/specs/response_validator.rb:19:in `validate!'
     # /Users/heaven/.rvm/gems/ruby-2.4.1@crm/gems/rswag-specs-2.0.5/lib/rswag/specs/example_helpers.rb:31:in `assert_response_matches_metadata'
     # /Users/heaven/.rvm/gems/ruby-2.4.1@crm/gems/rswag-specs-2.0.5/lib/rswag/specs/example_group_helpers.rb:91:in `block in run_test!'
     # ./spec/rails_helper.rb:184:in `block (3 levels) in <top (required)>'
     # /Users/heaven/.rvm/gems/ruby-2.4.1@crm/bundler/gems/vcr-6fb86f588e37/lib/vcr.rb:261:in `turned_off'
     # ./spec/rails_helper.rb:184:in `block (2 levels) in <top (required)>'
```

**Comment by jaydorsey** [comment]
I think what your `schema  type: :array...` &  schema definition is actually translating to isn't accounting for, _at least_ the outer `data` wrapper. If you weren't using jsonapi, using `type: :array` would make sense but you have to account for that additional top level key.

Can you try making your response schema something minimal, to check for the data key only basically? Something like below I think:

```
schema type: :object,
  properties: {
    data: { type: :array }
  } 
```

**Comment by heaven** [comment]
Hi, I've got your point, the following definition and spec worked:

```ruby
member: {
  type:       :object,
  properties: {
    attributes: {
      type:       :object,
      properties: {
        first_name: { type: :string },
        last_name:  { type: :string },
        email:      { type: :string }
      },
      required:   ['email']
    }
  }
}

schema type: :object,
  properties: {
    data: { type: :array, items: { '$ref' => '#/definitions/member' } }
  }
```

But I tried this to describe another schema, for a spec where we have `POST` requests and the generated docs don't look right:
<img width="806" alt="screen shot 2019-03-06 at 18 48 25" src="https://user-images.githubusercontent.com/126732/53898313-7f56f280-4040-11e9-805d-b4479e14ac5c.png">

You can see it suggests wrapping the data into `attributes` object, which isn't correct. Additionally, swagger UI doesn't highlight required fields with an asterisk.

I guess the validator should accept the original schema I provided previously and knowing that the response is supposed to be in `json` or `json_api` format (depending on the `ActiveModelSerializers.config.adapter` setting) and transform it accordingly. So the same schema would work for all 3 supported adapters. I mean when the format is set to `json_api` it's obvious there will be a root object (`data` by default or customized via the settings) and an additional `attributes` object. What do you think?

UPD. Or our API should accept JSON:API format as well because now it seems like a discrepancy between what our API produces and consumes... But then issue with required keys in nested attributes remains. Perhaps I should set required keys including the whole chain, like `attributes.keywords` instead of just `keywords`, like I used to.

**Comment by jaydorsey** [comment]
You need to click `Model` to see the required keys

![image](https://user-images.githubusercontent.com/191564/53975703-7a8f4e80-40d3-11e9-8055-0c642cf0f3cb.png)

What you're looking at is just an example document that you'd use if you clicked `Try it out` (see how it toggles to a textarea). If your required fields are documented properly they'll show on the Model. There's a flag to make the Model page show by default.

Here's an example of what you'll see on the model page, if you have a properly defined schema. The red asterisks are required.

![image](https://user-images.githubusercontent.com/191564/53976385-e45c2800-40d4-11e9-8db7-a4f41f1b7cf5.png)

In your rswag-ui.rb file:

    c.config_object[:defaultModelRendering] = 'model'

A list of config flags are here: https://github.com/swagger-api/swagger-ui/blob/master/docs/usage/configuration.md#configuration

If it suggests wrapping the data in an attributes object in your example, I'd venture a guess that maybe you've got an `example` defined, or else the schema is defined that way. If you can post it I'd be happy to take a look. If I remember correctly, it will present the schema as the example first, unless you've dfined an example inline. I think you may have a request schema defined w/ the attributes flag, because the `"string"` value is what it would show if you'd done so.

Rswag doesn't automatically do any wrapping for you of json_api/json so it _should_ be something that you've set.

I _think_ there's a way to make it show 3 different examples (json/jsonapi/xml for example) as you toggle the content type. The pet store example, at least, has xml/json content types and I seem to recall it toggling. I'd dig into their json file and then reverse engineer how you'd apply that to rswag (probably a Hash for the schema or something)

**Comment by pernambucano** [comment]
Hi everyone, awesome discussion. I just want to point one small detail: 
Rswag uses json-schema, and the last version of json-schema (2.8.1) only seems to understand until json-schema v4. So be careful with what schema you use to identify jsonapi (I'm currently using the one @jaydorsey mentioned). 

I'm trying to use jsonapi-resources with this amazing library, everything (except for the examples sometimes) works wonderfully. However, I'm having a hard time trying to add in the response schema the jsonapi schema + the actual response of the endpoint inside the data/attributes path.  

I see that you are showing just part of it (just the data part), in your example, @jaydorsey , but I can't for life of me do that using just json-schema stuff. Are you doing it dynamically somehow? Do you have an example to point me in the right direction? 

Btw, I've been reading tons of issues in this repo, and you helped so many of us noobs already, thanks a lot for all the work you've put in the issues section.

**Comment by jaydorsey** [comment]
> I see that you are showing just part of it (just the data part), in your example, @jaydorsey , but I can't for life of me do that using just json-schema stuff. Are you doing it dynamically somehow? Do you have an example to point me in the right direction?

I switched away from rswag about 6 months ago (new job) so I don't really recall exactly what I did. The last repo is private, but I do remember a couple details that might help:

- I used [json-schema_builder gem](https://github.com/parrish/json-schema_builder) for creating and managing schemas. IIRC, this is what generated the schema you see a partial screenshot of above. The gem is basically a nice DSL for describing your schemas.
  - I think I made some kind of really basic schema "loader", where the resources always had a matching `schema/<resource_name>.rb` file or something like that, which defined the schema
  - I do remember creating multiple schemas inside that file; I think I'd have an update schema (requires an ID, for example) & a create schema (doesn't need an ID) defined, for example. Because the actions have different fields
  - You can get pretty far with just starting w/ 1 schema in each but eventually you'll want to have a separate schema for each action you do

I do remember it seeming like a lot of duplicative work (create the parameters in the spec, create the schema file, etc.) but I remember being pretty happy with it even with the duplication. Yeah, you had to update the schema file every time you changed a parameter, and sometimes they were out of sync if I forgot, but it kept the concerns isolated and easy to find later

Also, you don't have to use the gem. I think my "first pass" at doing response schemas was doing JSON files for every resource, then I converted all those to YAML (again, with some kind of Loader file to convert it to JSON), then I found the gem around the same time I realized I needed at _least_ 3 schemas for every resource (create, update, and then a response) and thought the gem would help reduce some schema duplication.

I don't remember if it did or it didn't, but I do also remember that's what I ended up with, and I also explored creating one giant YAML and JSON file (as 2 diff attempts) and using references in it per the examples you see for JSON schema and not being super happy w/ it.

Sorry I couldn't help more

**Comment by heaven** [comment]
Whoops, I forgot I already opened one issue and here's another https://github.com/rswag/rswag/issues/321 I was able to workaround this by patching RSwag slightly.

**Comment by pernambucano** [comment]
Thanks a lot for the quick response, guys. I am right now using two schemas for an example. Let's say, I'd have a base schema (with the jsonapi schema) and a book schema. My target is to have a swagger like this :

![image](https://user-images.githubusercontent.com/6789675/84531675-526da280-acbb-11ea-85ee-6d7805afd101.png) 

So basically I'd only create a schema for that resource (inside the attributes part) and reuse the base schema. 

As I see, I could use the gem you talked about @jaydorsey  to create the resource schema and store it somewhere (could I create this schema on-demand to avoid have to change in the model/resource and the schema or would it make tasks too slow?).

I looked at your patch, but I didn't understand where to put the code for the SpecHelpers::Integration::ResponseValidator module, @heaven .

With it, would I be able to show the data/attributes in our swaggerui (i.e. the composition between the jsonapi schema and the resource schema) or  the whole resource schema (inside the data)?

Again,  thanks a lot guys.

**Comment by heaven** [comment]
@pernambucano in our project this helper lies in `spec/spec_helpers/integration/response_validator.rb` but it only works with JSON format, like this:
```ruby
user: {
  email: "...",
  name: "..."
}
```
and allows the following schema definition
```ruby
user: {
  type: :object,
  properties: {
    email: { type: :string },
    name: { type: :string }
  }
}
```
Without the patch I had to write definitions like this, which looks quite awkward and redundant:
```ruby
user: {
  type: :object,
  properties: {
    user: {
      type: :object,
      properties: {
        email: { type: :string },
        name: { type: :string }
      }
    }
  }
}
```
Which didn't still work properly in case of nested references and failed to validate references properly. For example in such case it would only validate the `user` object and wouldn't be able to validate `asset_image` because it also would be wrapper twice:
```ruby
user: {
  type: :object,
  properties: {
    user: {
      type: :object,
      properties: {
        email: { type: :string },
        name: { type: :string },
        avatar { '$ref' => '#/components/schemas/asset_image' }
      }
    }
  }
}
```
My patch fixes this.

Would require further modifications to work with JSON:API format and it probably won't be easy. We stopped using JSON:API due to unnecessary complexity and some other problems.

**Comment by pernambucano** [comment]
Thanks a lot for the patch, man. We will use it here too. 

We've arrived at a simple solution that has worked so far, but that we know it is not very scalable yet.

So we save the json_api scheme in a json somewhere, and create a method for composing both:

```ruby
def make_schema_resource(resource_schema)
  schema type: :object, properties: { 
    data: {
      allOf: [{"$ref" => 'json_api.json#/definitions/resource'}, resource_schema]
    }
  }
```
This has the benefit of validating the response for the json_api/resource format and the specific itens of the resource_schema. Also, it "joins" both schemas to make it look prettier on the swagger ui.  On the other hand, we can't specify yet other items like relationships.  

The resource schema would be saved somewhere and fetch using the advices @jaydorsey explained above. It currently stands like this:

```ruby
resource_schema = {
          type: :object,
          properties: {
            attributes: {
              type: :object,
              properties:{
                'first-name': {
                  type: :string
                },
                'last-name': {
                  type: :string
                },
                'email': {
                  type: :string
                }
              },
              required: ['first-name', 'last-name', 'email']
            }
      }
}
```

This gives us the swagger I printed above. However, we will have to write a lot of schemas by hand yet, but I think this is a limitation of working with jsonapi at the moment.
