### ISSUE TITLE
rswag spec conversion to json misses first file when using a substitute to "swaggerize" within a docker container

### ISSUE THREAD

**Issue by hasc34** [rswag/rswag#202]
1.) I have my spec files mounted into a docker container
2.) I tunnel into the docker container using: docker exec -it <<container_name>> bash
3.) I only want to swaggerize spec files within the /integration/ folder, so I run the command: rspec --pattern spec/integration/*_spec.rb --format Rswag::Specs::SwaggerFormatter --dry-run --order defined
4.) In the integration folder, I have the following structure:
/integration/ 
	- bbb_spec.rb
	- ccc_spec.rb
	- ddd_spec.rb

5.) When the swagger json generation completes successfully, the json only contains the information for ccc_spec.rb, and ddd_spec.rb
6.) I add a file to the integration folder. I now have the following data structure:
/integration/ 
	- aaa_spec.rb
	- bbb_spec.rb
	- ccc_spec.rb
	- ddd_spec.rb
7.) I rerun the same command as before: rspec --pattern spec/integration/*_spec.rb --format Rswag::Specs::SwaggerFormatter --dry-run --order defined
8.) When the swagger json generation completes successfully, the json only contains the information for bbb_spec, ccc_spec.rb, and ddd_spec.rb

**Comment by jtannas** [comment]
heyo - sorry it took so long for someone to respond 🙇
Since there's no actual code here to diagnose there's not much I can do to help you.
This issue is quite old and I'm trying to catch us up on the backlog so I'm going to close this issue now. If you're still running into problems then feel free to open a new issue and I'll be happy to help. Cheers!
