### ISSUE TITLE
Documentation doesn't match implementation for asserting headers

### ISSUE THREAD

**Issue by jonstorer** [rswag/rswag#218]
The documentation depicts the ability to define headers that need to exist in the response as well as some simple validation.

https://github.com/domaindrivendev/rswag#response-headers
```
header 'X-Rate-Limit-Limit', type: :integer
```
However the code the to validated the headers only checks if the key exists. It does nothing to validate the header value.

https://github.com/domaindrivendev/rswag/blob/master/rswag-specs/lib/rswag/specs/response_validator.rb#L36

```
def validate_headers!(metadata, headers)
  expected = (metadata[:response][:headers] || {}).keys
  expected.each do |name|
    raise UnexpectedResponse, "Expected response header #{name} to be present" if headers[name.to_s].nil?
  end
end
```

**Comment by jtannas** [comment]
heyo - I'm a new volunteer going through and cleaning up the issue backlog.
There's a very similar issue https://github.com/rswag/rswag/issues/484 that has some code to potentially fix the issue. I'm going to tag this as duplicate and close it so that we can keep all relevant discussion in one place. Feel free to hop in there if you'd like to discuss.
Cheers 🙂
