### ISSUE TITLE
rake rswag:specs:swaggerize reports a failure, but I don't know how to debug it

### ISSUE THREAD

**Issue by ndbroadbent** [rswag/rswag#220]
Output from `RAILS_ENV=test rake rswag:specs:swaggerize`:

```
$ RAILS_ENV=test rake rswag:specs:swaggerize
/Users/me/.rvm/rubies/ruby-2.5.5/bin/ruby -I/Users/me/.rvm/gems/ruby-2.5.5/gems/rspec-core-3.8.0/lib:/Users/me/.rvm/gems/ruby-2.5.5/gems/rspec-support-3.8.0/lib /Users/me/.rvm/gems/ruby-2.5.5/gems/rspec-core-3.8.0/exe/rspec --pattern spec/requests/\*\*/\*_spec.rb,\ spec/api/\*\*/\*_spec.rb,\ spec/integration/\*\*/\*_spec.rb --format Rswag::Specs::SwaggerFormatter --order defined
Generating Swagger docs ...
Run options: exclude {:type=>#<Proc:./spec/spec_helper.rb:42>}
Swagger doc generated at /Users/me/code/app/swagger/v1/swagger.json
Coverage report generated for RSpec to /Users/me/code/app/coverage. 2771 / 7593 LOC (36.49%) covered.
/Users/me/.rvm/rubies/ruby-2.5.5/bin/ruby -I/Users/me/.rvm/gems/ruby-2.5.5/gems/rspec-core-3.8.0/lib:/Users/me/.rvm/gems/ruby-2.5.5/gems/rspec-support-3.8.0/lib /Users/me/.rvm/gems/ruby-2.5.5/gems/rspec-core-3.8.0/exe/rspec --pattern spec/requests/\*\*/\*_spec.rb,\ spec/api/\*\*/\*_spec.rb,\ spec/integration/\*\*/\*_spec.rb --format Rswag::Specs::SwaggerFormatter --order defined failed
```

When I run the specs manually:

```
$ rspec spec/integration --order defined

Running via Spring preloader in process 6773
Run options: exclude {:type=>#<Proc:./spec/spec_helper.rb:42>}
...................................................................................................

Finished in 1 minute 14.73 seconds (files took 1.65 seconds to load)
99 examples, 0 failures
```

Also the `swagger.json` file is updated fine, so it doesn't look like anything is failing. I was just wondering why rswag reports the "failed" at the end. I can't see anything else in the console, and no output in `log/test.log`.

Thanks for your help!

**Comment by ndbroadbent** [comment]
Not sure what changed but I'm no longer getting a failure, so I will close this for now

**Comment by Petercopter** [comment]
@ndbroadbent It seems to have something to do with disabling the dry run, I'm having trouble debugging as well. The problem started when I added the config to `application.rb`

https://github.com/domaindrivendev/rswag#enable-generation-examples-from-responses

Edit: The task seems to be succeeding, it looks like I'm getting back the updated swagger.json, but it's reporting that it failed. This is inside a Docker container, I'm going to try shelling into the container and running the command there instead of using `docker-compose run` and see if that changes anything.
