### ISSUE TITLE
How to pass parameter in query with format   /subscriptions?filter[field]=value

### ISSUE THREAD

**Issue by alduro** [rswag/rswag#222]
## UPDATE: looks like this is possible in OpenAPI 3.0 only.

I got this Rspec failing when trying to pass `filter` parameter:

     
      parameter name: "filter", in: :query, required: false,
                schema: {
                  type: :object
                },
                style: :deepObject,
                explode: true,
                description: "Filters the subscriptions for the given business entity uri"

      response '200', 'filter subscriptions by business_entity_uri' do
        let(:dealer2_uuid) { SecureRandom.uuid }
        let!(:dealer2) { create(:dealer, dealer_type: "FLEET") }
        let(:business_entity_uri) { "decisiv:business_entities:#{dealer2_uuid}" }

        let(:filter) do
          {
            "buiness_entity_uri" => business_entity_uri
          }
        end

        before do
          dealer2.portal_dealer
            .update_column(:business_entity_uri, business_entity_uri)
        end

        schema '$ref' => '#/definitions/subscriptions'

        examples 'application/json' => SubscriptionExamples.subscriptions

        run_test! do |response|      
          expect(json_response[:business_entity_uri]). to eq business_entity_uri
        end
      end

Failures:

  1) API Fleet Subscriptions /api/v1/subscriptions get filter subscriptions by business_entity_uri returns a 200 response
     Failure/Error: example.run

     NoMethodError:
       undefined method `to_sym' for nil:NilClass
       Did you mean?  to_s

**Comment by jaydorsey** [comment]
Try this:

Change your parameter name from:

    parameter name: "filter"

to (I don't think the schema is necessary either):

    parameter name: "filter[business_entity_uri]"

Then your let to this:

    let(:'filter[business_entity_uri]') { business_entity_uri }

I'm actually doing these kind of nested filters with JSON::API now, using the above. I haven't tested it with trying to use a schema at all, so if I have two filters I write them out as separate parameters (rather than attempt to use a schema).

Update: Fixed the parameter name & added info on how I'm using these kinds of nested parameters

**Comment by heaven** [comment]
I have a similar use case:
```ruby
let(:search) do
  { keywords: 'Test keywords', filters: { with: { all_of: { field1: "test", field2: "test" } } }, favorite: true }
end

parameter name: :search, in: :query, schema: {
  '$ref' => '#/definitions/search'
}
```

The search object should pretty easily transform into params:
```
2.4.1 :097 > CGI.unescape({ search: { keywords: 'Test keywords', filters: { with: { all_of: { field1: "test", field2: "test" } } }, favorite: true } }.to_param)

 => "search[favorite]=true&search[filters][with][all_of][field1]=test&search[filters][with][all_of][field2]=test&search[keywords]=Test keywords"
```

But getting:
```
     NoMethodError:
       undefined method `to_sym' for nil:NilClass
     # /Users/heaven/.rvm/gems/ruby-2.4.1@crm/gems/rswag-specs-2.0.5/lib/rswag/specs/request_factory.rb:78:in `build_query_string_part'
```

**Comment by BookOfGreg** [comment]
@heaven Add this as a test in [request_factory_spec.rb](https://github.com/rswag/rswag/blob/master/rswag-specs/spec/rswag/specs/request_factory_spec.rb) and we can see about getting it fixed. This looks like it could be a bug.

**Comment by brcebn** [comment]
> ```ruby
> parameter name: "filter[business_entity_uri]"
> ```

Almost right. Just need to specify the type. Unless you'll have a `undefined method `to_sym' for nil:NilClass` ([request_factory.rb#L78](https://github.com/rswag/rswag/blob/master/rswag-specs/lib/rswag/specs/request_factory.rb#L78))

Then:

```ruby
parameter name: "filter[business_entity_uri]", type: :string

let(:'filter[business_entity_uri]') { business_entity_uri }
```

**Comment by mkalvas** [comment]
This looks like a bug to me.

[reuqest_factory#L121](https://github.com/rswag/rswag/blob/master/rswag-specs/lib/rswag/specs/request_factory.rb#L121) should be

```rb
return "#{name}=#{value}" unless param[:schema][:type].to_sym == :array
```

due to PR #286 changes 

>  - [x] Query and Path params `type:` to `schema: { type: }`

I can open a PR if that would help. ~~Am I wrong here?~~ I was wrong here.

## Follow Up

In the course of trying to fix the bug and open a PR, I found a better workaround. If we include both lines
```
type: :string,
schema: { type: :string },
```
in the parameter definition, it works. So… I'm not sure what the best path forward here is.

This core of the issue is that it runs one way (with the metadata node only having `type`) when run without `Rswag::Specs::SwaggerFormatter` and another way (with the metadata node using `schema: { type: ... }`) when run with the formatter. I think the upgrade request metadata logic in [swagger_formatter](https://github.com/rswag/rswag/blob/7ceedab4cb7788ab6b86b96bd2d8f2419e11ebbb/rswag-specs/lib/rswag/specs/swagger_formatter.rb#L148) is where this discrepancy is coming in. So should this be fixed in the `request_factory` by making the logic I referenced above more resilient? Or should the formatter be updated to give metadata to the `request_factory` that's consistent with RSpec metadata. I'm personally inclined towards making the request_factory more resilient (because keeping exact parity with RSpec seems like a brittle process), but that begs the question of what takes precedence when both are defined. Is there a use case or some valid configuration for a parameter that could use (for example) `type: :string, schema: { type: :array }` or something?

**Comment by mia-n** [comment]
@mkalvas that workaround doesn't hold up to the openapi-validator. Running the openapi-cli validate against a spec against a yaml in which you have left that yields:
```
Validating spec (/local/openapi/v1/openapi.yaml)
Errors:
        -attribute paths.'/your_path/'(get).parameters.[param_name].type is unexpected

[error] Spec has 1 errors.
```

More importantly in my case, this then also causes an error if you try to use the openapi-cli to generate a client from the yaml, which was the entire reason we tried adopting rswag in the first place.

**Comment by mkalvas** [comment]
@mia-n , you're right. There were bigger underlying issues here with openapi incompatibility that we came across as well. I forked and fixed for my immediate needs, so I need to put up a PR and get feedback from the maintainers. It's been a few weeks so I'll have to figure out if any recent work has changed the landscape here and I might not have time to get to it for another week or more. Also, our fix is the minimal fix for what we needed but it appears that there might be wider work that needs to be done.

**Comment by jtannas** [comment]
Added this to our FAQ since we've seen a lot of issues over time about it. https://github.com/rswag/rswag/wiki/FAQ#how-can-i-submit-arrays-through-query-parameters
Closing this issue now, but please feel free to open another if you're still having problems. Cheers! :slightly_smiling_face:

**Comment by heaven** [comment]
@jtannas I think `style` and `explode` params do nothing, where can I read about them? Also, it doesn't work when providing a `$ref` instead of the actual schema.

So technically the only way I could make it work was to specify the parameter name with `[]` at the end and providing the actual schema instead of the reference, which we normally never do, keeping all schema definitions in a single place.

This works
```ruby
parameter name: :"s[]", in: :query, style: :form, schema: {
        type:    :array,
        items:   { type: :string },
        example: ['path ASC', 'depth ASC', 'lang ASC', 'widget_installed ASC', 'crawled_at ASC']
      }
```
