### ISSUE TITLE
doesn't actually run tests

### ISSUE THREAD

**Issue by dan-ding** [rswag/rswag#24]
--dry-run is set on swaggerize-ation.

Is the plan to remove this at some point?

**Comment by domaindrivendev** [comment]
Well, I had thought this would be the desired behavior. As in ... people would want the running of tests be separate to the swagger generation.

However, your comment has me questioning this now. Perhaps it should run the tests also? I'd be interested to hear what others think?

**Comment by dan-ding** [comment]
Well, if it's not running tests, then why write the swagger stuff in them? There's other libs which can write swagger, but this is the only one with "testing" integration.

**Comment by domaindrivendev** [comment]
To be clear, the value prop. of swagger_rails isn't that the "test run" and "swagger generation" happen at the same time. That's just a preference, hence why I'm interested to hear other peoples thoughts.

The true value of swagger_rails, is that you only "specify" your API once and that canonical description can then be used to drive integration tests AND generate documentation (not necessarily with the same command)

**Comment by dan-ding** [comment]
I do see your point @domaindrivendev . Now I'm not sure what to think ;)

**Comment by drewish** [comment]
@dan-ding I also wanted the tests to be run so I could capture the output as examples. I found it really frustrating to generate the docs and then realize there was an error that wasn't reported during that time.

**Comment by domaindrivendev** [comment]
Check out the latest version 1.0.0. It should be Rails 5 compatible and also has lots of other great features added. NOTE: the name change from swagger_rails to rswag and the decomposition into components so you can pick and choose which parts you need. Also worth noting there's a minor breaking change - the "parameter" method in the rspec DSL now expects a single argument (attributes) that includes "name" instead of two arguments (name, attributes).

I'm going to close this issue because I still like the idea of separating tests from Swagger generation. However, if you want to do it all together, just run the following:

``` ruby
bundle exec rspec spec/integration --format Rswag::Specs::SwaggerFormatter --order defined
```
