### ISSUE TITLE
`rails rswag` deletes Seeds from DB

### ISSUE THREAD

**Issue by tristan-zellner** [rswag/rswag#272]
Everytime I run `rails rswag` my DB seeds are getting deleting. Why is that?

As long as I am on my local machine it's no big problem, but on other environments that would be a real pain. Is that on purpose or is there maybe a problem with my rswag Setup?

**Comment by Kutomore** [comment]
I once had a similar problem, running my tests would clean my development table. After some digging I fount out that the database cleaner on rspec was the culprit, and it was happening because my enviroment was mistakenly set as development while the tests were running. So something similar might be happening to you.

**Comment by tristan-zellner** [comment]
Yep, thats it. When I start it explicitly with `rails rswag RAILS_ENV=test` it works. There must be some misconfiguration with my environments I guess.

Thank you very much :)
