### ISSUE TITLE
Help Wanted?

### ISSUE THREAD

**Issue by akabiru** [rswag/rswag#280]
Dear @domaindrivendev @BookOfGreg,

Thank you for building this very useful tool and for continuously looking after it! 🍻 

I've noticed a bit of a struggle looking after issues & pull request and I was wondering if you'd like any assistance on this.

I would be happy to volunteer as a collaborator and I suspect there are other people in the community who'd be more than willing to support this project. I've seen a similar approach work very well with the [@faker-ruby](https://github.com/faker-ruby) community which I'm part of.

Lmk.

Best,
Kabiru

cc https://github.com/rswag/rswag/pull/167

**Comment by BookOfGreg** [comment]
Hi @akabiru,

I've been struggling to contribute since October as the company I work for was bought by a big parent company that is hostile to contributing to open source so I can no longer contribute on sponsored company time.

I have a few weeks holiday in March that I may use to get the OA3 work complete, everything else has been on pause until that one as that's been the big barrier to further adoption that I've seen.
I've added you to RSwag org and granted you Triage ability in the meantime which gives access over issues and PRs, I can see the work that you did for the linked PR is good quality and you took the time to help others in that thread, if you tag PRs for release I'll try get things out weekly and we can work closer in the future.

Welcome aboard 🍻 

Regards,
Greg

**Comment by akabiru** [comment]
> Hi @akabiru,
> 
> I've been struggling to contribute since October as the company I work for was bought by a big parent company that is hostile to contributing to open source so I can no longer contribute on sponsored company time.
> 
> I have a few weeks holiday in March that I may use to get the OA3 work complete, everything else has been on pause until that one as that's been the big barrier to further adoption that I've seen.
> I've added you to RSwag org and granted you Triage ability in the meantime which gives access over issues and PRs, I can see the work that you did for the linked PR is good quality and you took the time to help others in that thread, if you tag PRs for release I'll try get things out weekly and we can work closer in the future.
> 
> Welcome aboard 🍻
> 
> Regards,
> Greg

Thank you @BookOfGreg  - I'm sorry to hear about the unfortunate turn of events at your co. I'll carve out some time to do at least 1 review per ~day~ week and will tag the ones that are ready. Cheers. 🍻 

_I'll resolve this issue now._ 🙂
