### ISSUE TITLE
Parameter reference not respected

### ISSUE THREAD

**Issue by seanstory** [rswag/rswag#329]
If I have a parameter definition in my swagger helper like:

```
      :my_param => {
        :name => :my_param,
        :type => :integer,
        :in => :path,
        :required => true,
        :description => 'Unique key for a content source, provided upon creation'
      }
```

I want to be able to use it in my spec like:

```
parameter :$ref => '#/parameters/my_param'
```

However,  I get errors like:
```
documents api /endpoint/{my_param} get ok test returns a 200 response
     Failure/Error: raise InvalidURIError, "bad URI(is not URI?): #{uri}"
```
unless I add the `:in => :path` to the line in my spec (redundant to what's in my reference). Further, I get errors about the name not being present unless I add `:name => :content_source_key` to the spec (also redundant). I get other errors when I pass integers (seems to assume it's a string) unless I add a redundant `:type => :integer` to the spec.

In the end I have to have:
```
parameter :name => :my_param, :in => :path, :type => :integer, :$ref => '#/parameters/my_param'
```

Other parameters with `:in => :query` that are not required fail even if the reference has `:required => false`

Virtually anything that matters for the test seems to not be picked up if it's inside the `$ref`, which is leading to my generated swagger.json being really redundant.

**Comment by ricardo-kagawa** [comment]
I'm not 100% sure if this is the problem, but shouldn't that parameter definition be under `#/components/parameters/my_param` for OpenAPI v3?

JSON Schema would allow you to place your parameter definitions anywhere, as long as you would later reference the correct path with `$ref`, but I guess OpenAPI v3 limits your reusable definitions to `#/components/parameters/`. And under Swagger v2 you would put your parameter under `#/definitions/my_param` instead.

And I suspect tooling could enforce the OpenAPI specification and ignore whatever is outside what the specs would allow.

**Comment by seanstory** [comment]
I was using v2.0.5. I upgraded to v2.3.1, switched to `openapi: '3.0.1'`, and moved the parameter definitions as you suggested and still see these errors.

**Comment by seanstory** [comment]
https://github.com/rswag/rswag/blob/master/rswag-specs/lib/rswag/specs/request_factory.rb#L121 looks to be at least one of the problems - requiring the param to have a `:type` key, not checking in the `$ref`

**Comment by ricardo-kagawa** [comment]
> https://github.com/rswag/rswag/blob/master/rswag-specs/lib/rswag/specs/request_factory.rb#L121 looks to be at least one of the problems - requiring the param to have a `:type` key, not checking in the `$ref`

Yeah, I have stumbled upon that particular line (and that's why I came across this issue in the first place).

If you compare Swagger v2 specs with OpenAPI v3 specs, you'll notice that the definitions for parameter descriptions are slightly different, which may have not been picked up by the guys working with `rswag`'s OpenAPI v3 support (the change is a bit subtle after all). This is something I only noticed after posting the answer above, and it took myself a long while to notice the difference.

OpenAPI v3 support is rather new, so I would not be surprised if it was buggy in places. The `rswag` DSL does not seem to have adjusted to the new version anyway, so request bodies are still described as parameters (OpenAPI now has a separate property for them), and parameter schema are still contained in the parameter itself, rather than under a `schema` property. But that is understandable, as `rswag` has to be able to output schemas in both versions... I digress.

The expected OpenAPI v3 output for your parameter in JSON format should then be:

```json
{
  "name": "my_param",
  "in": "path",
  "required": true,
  "description": "Unique key for a content source, provided upon creation",
  "schema": {
    "type": "integer"
  }
}
```

And I don't know if `rswag` should be expected to support this new format as input, or if we should use the Swagger v2 format as input and let `rswag` handle the conversion? Not my decision, I'm really just a random guy here. I myself just monkey-patched that method for a quick and dirty solution (very bad, I know).

**Comment by qbantek** [comment]
I am observing the same issue (using version 2.5.1)

**Comment by richardonrails** [comment]
Can this be reopened? I'm having the same issue - trying to simply say `      parameter '$ref': '#/components/parameters/pageParam'` in each API endpoint but getting Swagger validation errors. I'm using openapi: '3.0.1'

**Comment by richardonrails** [comment]
I think my issue was something else (OpenAPI validation error messages aren't the most readable!). I did get parameter references working using OpenAPI 3.0.3 now. 

My swagger_helper.rb has this:
```rb
        parameters: {
          pageParam: {
            name: :page,
            in: :query,
            description: 'Page Num',
            schema: {
              type: :integer,
              default: 1,
            },
          },
        },
```

And my endpoint specs have this:

```rb
      parameter '$ref': '#/components/parameters/pageParam'
```

And it works fine.
Not sure if @qbantek is still having issues but don't keep this open on my behalf.
