### ISSUE TITLE
Not generate response example

### ISSUE THREAD

**Issue by PvPenny** [rswag/rswag#337]
Hi,

I'me trying to save example response on Rails 6.0.3 app with

```
after do |example|
    example.metadata[:response][:examples] =
      { 'application/json' => JSON.parse(response.body, symbolize_names: true) } if response.body.present?
  end
```

In test.rb i've added this
```
  RSpec.configure do |config|
    config.swagger_dry_run = false
  end
```

but example respons is still blank. If i use
```
 response '200', 'test' do
        examples 'application/json' => {
            id: 1,
            title: 'Hello world!',
            content: '...'
          }
```
it works, but i want auto generation.
I use rswag v 2.2.3

**Comment by pernambucano** [comment]
Hi, you should probably look here #302

**Comment by olegykz** [comment]
The issue duplicates https://github.com/rswag/rswag/issues/325 - you can find a workaround there

**Comment by phlegx** [comment]
**Rswag:** 2.3.1
**Rails:** 6.0.3.2

Can someone help me please? I have the same problem. I have added `swagger_dry_run` to test environment, etc. but what I don't understand is, how you start a task to generate automatic examples.

What do you use?

`> rspec`
`> rake rswag`

I ask because `after do |example|` is only called if I run with command `rspec`. Do I miss something?

**Comment by jjercx** [comment]
I'm having same issue. @phlegx did you solve it?

**Comment by jjercx** [comment]
I tried searching for a workaround in #302 and #305 without success

**Comment by volkov-sergey** [comment]
@jjercx try this one `SWAGGER_DRY_RUN=0 RAILS_ENV=test rails rswag`

**Comment by coins-black** [comment]
> 

solved my problem

**Comment by coins-black** [comment]
> @jjercx try this one `SWAGGER_DRY_RUN=0 RAILS_ENV=test rails rswag`

solved my problem

**Comment by sergioisidoro** [comment]
Dry run also solved my problem. Any idea why the `config.swagger_dry_run = false` is not working?

Should the docs be updated? I lost a couple of hours on this trying to understand what was wrong...
https://github.com/rswag/rswag#enable-auto-generation-examples-from-responses

Edit: seems to be fixed in the yaml, but no in the ui due to the above mentioned issues

**Comment by lucasocon** [comment]
I left this comment with some information and a link to the doc:
https://github.com/rswag/rswag/issues/511#issuecomment-1131966609

Is this issue solved and could be closed?

**Comment by akaJSaunders** [comment]
Just wanted to contribute to the conversation by saying that I was struggling with the exact same issues for a few weeks, and then yesterday after updating the rswag gems to the latest version, it started working fine. Hopefully this helps some of you out there 🥲

**Comment by nelalampetal** [comment]
I saw in this issue https://github.com/rswag/rswag/issues/359#issuecomment-728836401

 put it into the Rakefile and worked for me running only command `rake rswag`

```
require_relative 'config/application'

# Workaround for https://github.com/rswag/rswag/issues/359
if defined? RSpec
  RSpec.configure do |config|
    config.swagger_dry_run = false
  end
end

Rails.application.load_tasks
```
