### ISSUE TITLE
Fail to load swagger-ui assets

### ISSUE THREAD

**Issue by sziep** [rswag/rswag#35]
Hi @domaindrivendev,

First of all: I love rswag as it saves me a ton of typing and keeping stuff in sync. Thank for your effort and time spent on this. 👍 

I have one issue with loading the swagger-ui assets in production environment. They get precompiled as I see all of them having digest, but the index.html.erb links them without the digest.

Im using rails 5.0.0.1 and rswag 1.0.3
I generated my own index.html.erb file via 'rails g rswag:ui:custom' and also tried to turn the `link` and `script` tags into rails `stylesheet_link_tag` and `javascript_include_tag`. This changed nothing.

all asset configs in my environments/production.rb:
config.assets.compile = false
config.assets.js_compressor = :uglifier

Any pointers what I'm missing or an idea how to fix this?

**Comment by domaindrivendev** [comment]
@sziep - thanks for the support.

To keep things simple, I wanted to take the swagger-ui assets in their raw form, which I believe to be prod-ready, minified etc., and dump them into the "vendor" folder of the Rswag::Ui::Engine without transforming to use any rails-specific conventions for assets. This way, upgrades will be very simple.

This alone works well in dev environments because the asset pipeline is smart enough to look into Engine vendor folders for asset requests. However, in prod the asset pipeline is typically disabled. So, these assets need to be copied to the hosting app's "public" folder on asset precompile. I accomplished this with the following snippet in _rswag/ui/engine.rb_:

``` ruby
class Engine < ::Rails::Engine
  isolate_namespace Rswag::Ui

  initializer 'rswag-ui.initialize' do |app|
    if app.config.respond_to?(:assets)
      app.config.assets.precompile += [ 'swagger-ui/*' ]
    end
  end
end
```

So, the assets are being flagged for precompile, but really just as a means of getting them copied into the app's "public" folder. There's actually no difference between the digest and non-digest versions.

I guess this isn't ideal because now there's duplicated assets on your server (maybe there's a better way of accomplishing this) but from a functional perspective I don't expect there to be a negative impact using the non-digest versions.

**Comment by sziep** [comment]
Alright, I understand your reason behind this. The thing is, I don't get any non-digest versions generated. Only assets with digest ending are up in my asset folder

**Comment by domaindrivendev** [comment]
Ahh - well that is a problem. I need to figure out an alternative then

**Comment by domaindrivendev** [comment]
@sziep - I've found a solution that should resolve this but before I go ahead and push it out, it would be great if you try it with your custom index.erb as a kind of live test? Basically, just use a combination of ERB and the **asset_path** helper to resolve all urls in your template as follows:

``` html
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>Swagger UI</title>
  <link rel="icon" type="image/png" href="<%= asset_path 'swagger-ui/images/favicon-32x32.png' %>" sizes="32x32" />
  <link rel="icon" type="image/png" href="<%= asset_path 'swagger-ui/images/favicon-16x16.png' %>" sizes="16x16" />
  <link href="<%= asset_path 'swagger-ui/css/typography.css' %>" media='screen' rel='stylesheet' type='text/css'/>
...
```

This worked for me in dev/test and production rails environments with the digest version being used in the latter

**Comment by sziep** [comment]
It did not exactly work for me, but this may due to my setup with docker. I have found a way to make it work for me. I ditch the precompiled assets in public folder and copy them from the gem source. Its not the most elegant solution, but its part of the docker image building and I can live with it for now. 

Thank you for your time and effort.
Have a nice day

**Comment by domaindrivendev** [comment]
Fair enough. It would be helpful though to know why the proposed fix isn't working for you as it's not clear to me why running in a Docker container could be the cause.

If there's an issue, I'd like to get to the bottom of it. Thanks

**Comment by pbelouin-mpiwg** [comment]
Hi There! First, thanks for this awesome gem, it's really neat and useful. I pretty much have the same issue, using docker and nginx to serve the static assets - I can see that the swagger-ui assets are getting precompiled, but do not end up in the docker volume I use to serve the assets, and I have no idea why - I've tried a few different things to no avail. so @sziep I'd be very grateful if you could tell me in a bit more detail how you manage to solve this issue!
