### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by joeytheman** [rswag/rswag#355]
I noticed there are a bunch of outstanding PR's. Is this gem still actively maintained?

**Comment by BookOfGreg** [comment]
It is every now and then.

More help is always welcome especially if you have a particular area you care about.
I think there are 4 of us with write access to the repo currently.

**Comment by telyn** [comment]
It looks like it's just you remaining as a member of the RSwag organisation. (Can you keep your own personal organisation membership a secret on github? Might explain it)

Assuming that it is true, though, is there any way non-members can help reduce the burden on you (for example, reviewing/triaging PRs)?

**Comment by joeytheman** [comment]
Reviewing the open PR's, quite a few people have submitted fixes for very similar issues. 

@BookOfGreg  - would you be able to put together a set of guidelines/rules (ie not breaking tests, proper coverage, etc) for merging PR's and identify what milestones you would like to achieve for the next release?  I think once you have that, you can delegate those tasks to other members of the community.

**Comment by BookOfGreg** [comment]
Yes you can hide or show organization membership so I think I may be the only one to show up. There is still at least the original creator, and the developer of an influential fork who have primary access to this repo whether it shows up or not.

Part of the reason for the slow down on my part is my company no-longer sponsors any OS dev which was the main source of time I spent here and on react-rails also, and due to real life I've been doing woodwork in my spare time rather than programming to keep my sanity. I do intend on spending more time here once things are a little more normal.

For guidelines, it is mainly make sure important branches of code and data structures are covered by tests, since this gem heavily uses internal rspec metadata it's surprisingly easy to break something.
For milestones it's primarily just increase coverage of OpenAPI3 spec, so examples are a major one, as are any other missing feature.

Edit: To add in, I do want to add more people officially to maintain and triage and release versions of both this and react-rails also. Just hard to choose when I need to be worried for the safety of the gem and it's users that no bitcoin/phishing/hacked one ever gets released so I'm slow to trust and add more folk, I hope that's understandable. Anyone with experience maintaining other projects on github or elswhere are more eligible.

**Comment by joeytheman** [comment]
I think there are a few small things that can done to remove a bit of the burden on maintainers of this project and to spur more active community involvement.

1. Would you be able to add the guidelines to say a `CONTRIBUTING` file or contributing section in the `README`? 

2. Can you enable the test coverage checks on PR's through the Github repo settings? This will easily let the community know if their PR is breaking an existing feature.

3. Can you add Code Climate PR diff-coverage, where you can automatically reject PR's if it drops below a threshold. https://docs.codeclimate.com/docs/configuring-your-analysis

4. Can you add the milestone as a Github milestone for the next major release version? A small blurb in the readme or `CONTRIBUTING` can also be informative to let others know the future direction of the project and how they be apart of that vision.

I feel these changes will provide more clarity on how other members of the community can participate in the advancement of rswag while reducing the load on the current maintainers. Essentially, the maintainers could just provide feedback and give the final stamp of approval to merge the PR's.

What are your thoughts?

**Comment by jamie** [comment]
I'm on a project at work that is really excited to use rswag for self-verifying API docs (a bigger win than we'd thought). We're standing up a new rails app currently, and looking to retro-fit into another two apps eventually - mixed internal/external documentation.

Due to a few missing features so far (the biggest being example responses), I've started to stand up a fork at https://github.com/jamie/rswag to un-block my work's usage, with the following changes:

- Added CI on GitHub actions, since Travis looks like it stopped builds. 
- https://github.com/rswag/rswag/pull/330 response examples
- https://github.com/rswag/rswag/pull/334 Documentation change
- Also started adding/organizing some of the output specs based on headings in https://swagger.io/docs/specification/about/ to help myself identify some edge cases to cover.

I don't know how many work-hours I'll have available (I would expect just enough to unblock any specific issues we're running into) but at a minimum I can throw a few hours a week into the Issue/PR backlog.

@BookOfGreg If that sort of thing sounds reasonable to you, I'm very open to help out on triage and general housekeeping, if you're willing. More than happy to just open up PRs as I go, but if you're comfortable giving me Triage permissions I'll happily start labelling stuff and tag you for focused code review. And then see where we go from there.

**Comment by jamie** [comment]
For the folks following along, Greg's got me some permissions. I don't want to step on his toes pushing anything to master, but I'm doing some PR grooming and have started a WIP branch where I'm merging (& logging) some approved PRs to do some conflict resolution and pass them through CI.

**Comment by BookOfGreg** [comment]
And you're off to a flying start, glad to have you on-board and thank you for accepting to help us.

**Comment by joeytheman** [comment]
Awesome! Welcome aboard @jamie . If you can create some milestones, I can see about getting some time allocated at work to help out with the next major release.

**Comment by joeytheman** [comment]
We're currently using the https://github.com/modernmsg/rswag branch with example printing.

**Comment by freiden** [comment]
Hello, sorry to be adding to the stress that this kind of thread could create but maybe can you indicate the current status of the gem and maybe update the README to indicate that your looking for more active contributors.

**Comment by oblakeerickson** [comment]
@freiden and everyone, just wanted to introduce myself and let you all know that I just got commit rights to this repo.

I use rswag at my job and so I want to make sure this project succeeds and I also try and contribute to open source projects when I can. 

I'm still getting familiar with this code base but I'll be working on steadily merging in The open PRs so that we can cut a new release. 

Feel free to message me directly or open an issue if you have any questions.

**Comment by jamie** [comment]
@oblakeerickson I've been pretty swamped lately with some other dayjob stuff, but I did set up some proposed 2.3.2 and 2.4 release milestones, I was _planning_ on setting up some clean-ish PRs to master that consolidate those things, essentially suggesting a draft gem release, for Greg to merge + cut a gem. If you're looking for some easy wins to start :)

**Comment by oblakeerickson** [comment]
@jamie yep I'm going to work on those next, thank you very much for all of your review work :)
