### ISSUE TITLE
API documentation path

### ISSUE THREAD

**Issue by freiden** [rswag/rswag#384]
Hi,
it seems like after the following the configuration indicated in the README I didn't find a way to serve the API doc of my app without putting the `api-docs` folder into the rails app `public` folder`. Without this trick I have the following message
![Capture d’écran 2020-11-30 à 11 57 12](https://user-images.githubusercontent.com/68886/100601685-327e7980-3303-11eb-8188-1abefce06508.png)

I tested with the code from the `test-app` and it works.
After analyzing the main differencies I'm using the YAML version of the swagger file and I disabled the API Engine that I'm not using. When adding the swagger-api engine in my routes it works.

Is it normal to have the api engine when I only want to display the swagger doc?

**Comment by oblakeerickson** [comment]
Yes, with a sample app that I made I also have to have the `api-docs` folder inside of the rails app `public` folder, but it works without the needing swagger-api engine.

The test-app appears to be working a bit different and I think the swagger-api engine may be taking precedence with it's config file `c.swagger_root = Rails.root.to_s + '/swagger'` which is why the test-app docs are loading that way.

You should not have to have the api engine if you only want to display the swagger docs. Is it okay if you load them from the public folder? That is kind of how rails works by default is that assets should be loaded from the public directory.

**Comment by freiden** [comment]
The issue if I load it from the public directory seems to be that the file will be available to anybody without constraint. And I would like to restraint the access to the file for people outside of my company.
Any tips maybe on how to do this?
