### ISSUE TITLE
Refused to connect to '/api-docs/v1/swagger.yaml' because it violates the following Content Security Policy directive: "default-src 'none'".

### ISSUE THREAD

**Issue by ewangx** [rswag/rswag#409]
I have an application using rswag on a remote server. But it's failing to load with the error:
```
Failed to load API definition.

Fetch error
Failed to fetch /api-docs/v1/swagger.yaml
```

Upon inspecting the developer console, I see:
```
Refused to connect to '/api-docs/v1/swagger.yaml' because it violates the following Content Security Policy directive: "default-src 'none'". Note that 'connect-src' was not explicitly set, so 'default-src' is used as a fallback.
```

I've tried setting `c.swagger_headers = { 'Content-Security-Policy' => "default-src 'self';" }` in rswag_api.rb, but that doesn't seem to work. Anyone have ideas?

**Comment by anupamkakade** [comment]
Seeing the same error 
```
Chrome Version 89.0.4389.114 (Official Build) (64-bit)
Firefox 87.0 (64-bit)
Rails 6.1.3
rswag (2.4.0)
```

![swagger_doc_error](https://user-images.githubusercontent.com/11293347/114053580-b09fed80-98ac-11eb-9619-63b5d64d5c05.png)

**Comment by jtannas** [comment]
heyo - new volunteer here helping to sort through the issue backlog.
This looks like it's a duplicate of #174 There's some important discussion there, including a PR that could potentially resolve the issue.
I'm going to mark this issue as duplicate and close it just so that we can focus the discussion in one place. Thank you for contributing though!
