### ISSUE TITLE
Problem with tags auto generation

### ISSUE THREAD

**Issue by shuiiiiiimu** [rswag/rswag#420]
According the doc of `Getting Started`, using `rswag=2.4.0` generate rspec from controller.

But not found `tags` in spec file.

**Comment by Peredery** [comment]
@shuiiiiiimu  did you find what the problem is?

**Comment by jaydorsey** [comment]
@shuiiiiiimu Can you post an example where the `tags` aren't getting picked up?

Most often I've found when this happens it's because I have the `tags` command listed in the wrong "place". It needs to be inside the post/get/delete/put "do" block. 

There are other places you can put it where it doesn't do anything, and still others you can place it where it errors

**Comment by jtannas** [comment]
heyo - I'm a new volunteer sorting through our issue backlog and found this.
Since it has been so long without a response or more details I'm going to close the issue.
Feel free to open another if you're still running into problems and we'll be happy to help. Cheers 🙂
