### ISSUE TITLE
How to optional query parameter

### ISSUE THREAD

**Issue by truonglocbinh** [rswag/rswag#430]
When I click Execute button, I want to `page`, `per_page`, `admin_user_id` is optional. But it still required also I set required: false.

```
      parameter name: :page, in: :query, type: :integer, required: false, description: 'Page number of the results to fetch. Default: 1'
      parameter name: :per_page, in: :query, type: :integer, required: false, description: 'Results per page (max 100). Default: 10'
      parameter name: :admin_user_id, in: :query, type: :integer, required: false, description: 'If you want to filter by admin user'
```
<img width="1234" alt="Screen Shot 2021-06-02 at 08 46 27" src="https://user-images.githubusercontent.com/8655190/120411602-4329ae00-c37f-11eb-8004-a345ba05b9bc.png">

**Comment by truonglocbinh** [comment]
I closed this issue because I figure out problem from me.

**Comment by AlexCs389** [comment]
Hello, I have the same problem, what was your solution?

**Comment by serg2801** [comment]
Hi @truonglocbinh 
I have same issue. How you resolved it?

**Comment by glenpike** [comment]
If anyone else runs into this problem. I had `required: :false` in my rspec parameter configuration rather than `required: false` as a typo - if you have that it generates JSON with `required: "false"`.  You can omit the required key if it is optional and it will generate the swagger ok too.
(if Swagger UI is using JavaScript, the string "false" will actually evaluate as true when cast to a Boolean, so guess that maybe the problem 🤷 - try `!!"false"` in your favourite JS console)
