### ISSUE TITLE
Separating test cases to separate files?

### ISSUE THREAD

**Issue by DeltaRazero** [rswag/rswag#466]
I am currently working on an API of which the spec files are grouped by controller and user-type scope. Some controllers have quite a number of possible actions and responses. Some require a large number of test cases to have full code coverage, leading to some files being almost at a thousand lines.

I was wondering if there was an elegant way of separating the test cases from describing the API, perhaps by including a function from a defined module (to avoid function naming conflicts but still having consistent function names), or something similar? Perhaps this gem provides something for this that I may have missed?

**Comment by jtannas** [comment]
I don't think there's any official guidance with this gem for the layout of your request specs - it really comes to what makes sense for your project.

That being said... What's worked so far for me is to break out the request specs by URL instead of by controller.
eg.
```bash
$ tree backend/spec/requests/api/v1/

├── organizations
│   ├── __organization_id__
│   │   └── url_spec.rb
│   └── url_spec.rb
├── sessions
│   ├── change_email
│   │   └── url_spec.rb
│   ├── change_password
│   │   └── url_spec.rb
│   └── url_spec.rb
└── users
    ├── confirmation
    │   └── url_spec.rb
    ├── invitation
    │   ├── accept
    │   │   └── url_spec.rb
    │   ├── remove
    │   │   └── url_spec.rb
    │   └── url_spec.rb
    ├── url_spec.rb
    └── __user_id__
        └── url_spec.rb
```

The benefit is we instantly know where to find the description for a URL. (eg. `GET /api/v1/users/123` -> `/backend/specs/requests/api/v1/users/__id__/url_spec.rb`). It's also useful if you're generating specs from an existing set of urls.
The downside it makes for A LOT of files.

Another pattern that might work for you is having one file per controller action
eg.
```bash
$ tree backend/spec/requests/api/v1/

├── organizations_controller
│   ├── create_spec.rb
│   ├── destroy_spec.rb
│   ├── get_spec.rb
│   ├── index_spec.rb
│   └── update_spec.rb
├── sessions_controller
│   ├── change_email_spec.rb
│   ├── change_password_spec.rb
│   ├── create_spec.rb
│   ├── destroy_spec.rb
│   └── get_spec.rb
├── users_controller
|   ├── confirm_spec.rb
|   ├── create_spec.rb
|   ├── destroy_spec.rb
|   ├── index_spec.rb
|   └── update_spec.rb
└── invitations_controller.rb
    ├── get_spec.rb
    ├── create_spec.rb
    ├── destroy_spec.rb
    ├── index_spec.rb
    └── update_spec.rb
```

**Comment by dollerbill** [comment]
@DeltaRazero My solution was to create a `contexts/swagger.rb` file, and in this context I have all Rswag test cases defined in individual shared examples (with shared context) for each route and status code.

In my existing controller specs I include the relevant Rswag examples with something like
```
  describe 'Swagger documentation tests' do
    include_context 'swagger'
    include_examples 'swagger_orders_controller'
  end
```
