### ISSUE TITLE
Are there maintained alternatives to RSwag?

### ISSUE THREAD

**Issue by joshbuker** [rswag/rswag#468]
Looking around at the issues, it looks like rswag isn't really maintained anymore. Are there any popular alternatives, or anyone interested in helping maintain RSwag?

**Comment by jimbali** [comment]
How many people actually have the right permissions to merge PRs and/or push to Rubygems in this project? Doesn't look like many as the last release was 11 months ago. 😩

**Comment by sergioisidoro** [comment]
It's quite frustrating seeing PRs that are reviewed, and ready for merge, and so many people engaging in the discussions, but no merges happening.

I've sent an email to Greg asking if he would like some help. (ping here as well @BookOfGreg @oblakeerickson )
Otherwise if anyone here is interested in joining me to maintain a fork of this repo, please let me know.

**Comment by jimbali** [comment]
I'd be happy to help maintain this repo or a fork, but I can't promise I'd be able to devote a lot of time to it.

**Comment by domaindrivendev** [comment]
@sergioisidoro - I'm the original creator of rswag (and owner of the rswag github org) and would be willing to grant you the neccessary privileges, if you feel you have the time to help keep this project thriving. Believe me when I say these projects take a lot of personal time, particulary as they get more popular - you may have the energy (and likely work-related mandate) to give it time right now, but inevitably that will change and the fork you create will also suffer from lack of maintenance. I've seen this same pattern repeat itself time and time again.

**Comment by joshbuker** [comment]
I can definitely echo @domaindrivendev's comments on energy maintaining projects.

It sounds like we have both the original maintainers, and some volunteers interested in helping at least for the short term. My thoughts are that the best solution would be to add them onto the team to help out, and to avoid any unnecessary forks.

**Comment by domaindrivendev** [comment]
Sounds like first order of the day will be to get an up-to-date release out. It seems there's been a number of commits to master since the last one and so we'd need to figure out if there's any potential breaking changes. If someone was willing to walkthrough the diffs and confirm we have no breaking changes committed since the `2.4.0` tag, then I'd be happy to push out a release. Once that's done, I can add some folks to the list of maintainers

**Comment by domaindrivendev** [comment]
@athix and @sergioisidoro - sounds like you're both interested in helping out, at least in the short term?

**Comment by joshbuker** [comment]
@domaindrivendev I wish I could, but I have my hands full with existing commitments. I do look forward to seeing some movement on rswag though, as I use it for some of my projects.

@jimbali and @sergioisidoro seem to both be interested in helping out however.

**Comment by sergioisidoro** [comment]
I can dedicate some time in the sort term, yes. And I totally agree that as time goes by the energy and enthusiasm dies out. But I think the important thing is that we pass on the torch to responsible people who show interest when that happens, and be transparent about our inability to contribute when it does :)

**Comment by sergioisidoro** [comment]
> confirm we have no breaking changes committed since the 2.4.0 tag

https://github.com/rswag/rswag/compare/2.4.0...master

Nothing seems to stand out as a breaking change, although CI in master has failed on the last merge. A first step would be to re-trigger those workflows to see if anything is broken.

**Comment by AhmedKamal20** [comment]
> Sounds like first order of the day will be to get an up-to-date release out. It seems there's been a number of commits to master since the last one and so we'd need to figure out if there's any potential breaking changes. If someone was willing to walkthrough the diffs and confirm we have no breaking changes committed since the `2.4.0` tag, then I'd be happy to push out a release. Once that's done, I can add some folks to the list of maintainers

> > confirm we have no breaking changes committed since the 2.4.0 tag
> 
> [2.4.0...master](https://github.com/rswag/rswag/compare/2.4.0...master)
> 
> Nothing seems to stand out as a breaking change, although CI in master has failed on the last merge. A first step would be to re-trigger those workflows to see if anything is broken.

@sergioisidoro Thank You 
@domaindrivendev just a reminder

**Comment by jtannas** [comment]
I'd like to volunteer as well.
As much as maintaining open-source takes energy, it's a lot less energy than overhauling a company's entire request test suite.

Maybe we start with giving some people triage permissions to the repo?
That way we can start doing a lot of the frontline issue support & initial PR review to lessen the burden on maintainers.

**Comment by BookOfGreg** [comment]
I'm thankful that so many of you have raised a hand in the comments.
Currently there's a lot going on in my life and have had to stand back from direct action but there are some PRs merged here and there.

I've been holding off on releasing as a gem due to lack of time to validate it on Rails 7 and if I released something broken it would stay broken for a while before I can roll it back.

There are currently 4 people who are members of the Org (see [here](https://github.com/orgs/rswag/people), some memberships are private), all who can write to the repo and release versions of the gem, however this is clearly not enough and we want to bolster this gem! Totally echoing @domaindrivendev above with the comments on time commitments and ties to the workplace, open source is hard, and time for it can come and go, life is constantly changing.

I've replied to Sérgio about including him in the repo as I checked email before GitHub today, but the door is open to more maintainers, especially ones that have contributed to other Orgs and have an established trustworthy record.
As one of the Org members my main concerns are is the gem safe from malicious actors, is it patched correctly, do the tests run, can I maintain existing functionality. This is why I have merged but not released for multiple months, simply not had time to check yet.

To be clear I got involved the same way you all did, which is I reached out to @domaindrivendev (Hi!) and asked if I could help. Lets give some of you a chance.
@sergioisidoro I have already emailed. @athix looks like @domaindrivendev is talking you through it already.
Keep up the pressure on us, we want help, but we don't always have the time to seek it ourselves.

**Comment by BookOfGreg** [comment]
Separating this commit to be super specific.
The biggest problems in this repo as I see them:
- [x] We need to regain trust in CI, GitHub Actions needs to be running green on all current rubies. Edit: https://github.com/rswag/rswag/pull/475
- [x] The world moved on a bit, we need compatibility with Rails 7, Turbolinks latest, Webpack/er latest. Edit: https://github.com/rswag/rswag/pull/481
- We don't have complete coverage of OpenAPI 3, majority of PRs are about adding some aspect of OpenAPI3 such as form data, nullables, param serializers etc.
- Some good practice work (removing `.send`, adding Ruby 3 to CI etc.)

**Comment by BookOfGreg** [comment]
@domaindrivendev 
Since you last worked on the gem, Travis.ci stopped providing free time for FOSS.
Tests have moved to GitHub but in order for @sergioisidoro and I to perform a release, we're going to need to you to either do the releases or if you put a rubygems key in the org secrets then we can construct a GH Action to release the gem without seeing the secret itself.
https://github.com/organizations/rswag/settings/secrets/actions
Edit: You could also grant me permission to release the gem myself on Rubygems, I already have push access for react-rails which is similarly large. https://rubygems.org/profiles/BookOfGreg

**Comment by sergioisidoro** [comment]
@BookOfGreg while we wait, should we organise things a bit

My proposal
- (maybe not necessary since we're so close) Create a milestone for Rails 7
- Create a Milestone for OAS3
- Create a Milestone for OAS3.1
- Group issues and Pull requests into those milestones, and do a first triage round
- Create a project board to further triage the issues into how far they are in the pipeline

I can do that if you want, if you give me permissions to manage the issues.

**Comment by BookOfGreg** [comment]
> I can do that if you want, if you give me permissions to manage the issues.

@sergioisidoro Upgraded you to "maintainer" access. I'll be honest I thought member on the org would have given you that but it's granted now.
For me the main thing is to get the gem release into GH Actions but only @domaindrivendev can provide the secret for rubygems, once that happens then yourself (AND OTHERS, MAINTAINERS WELCOME!) can take it as far as you want from there.

**Comment by BookOfGreg** [comment]
Sorry @domaindrivendev and @sergioisidoro appears I'm wrong again, that's what I get for being away from open source for a year.
The travis build and release is here https://travis-ci.org/github/rswag/rswag
@sergioisidoro you can release the gem that way still! Edit: Looks like it needs a migration.
I do think we should move onto GitHub actions for it but we can actually still cut a new gem.

**Comment by sergioisidoro** [comment]
I created a tag, and it seems that this repo might be still using the old Travis CI, because there was no effect:
https://github.com/rswag/rswag/releases/tag/2.5.0.rc1

I assume it's because of this:

> Since June 15th, 2021, the building on travis-ci.org is ceased. Please use travis-ci.com from now on.

So @domaindrivendev we would need you help either to migrate to the ravis-ci.com, or to configure the ruby gems secret in the github org as a repo secret.

As @BookOfGreg mentioned, he is also the maintainer of react-rails ( https://rubygems.org/profiles/BookOfGreg ), with 17M downloads. I think it's sufficient social proof that he's doesn't have malicious intent 😅 Could you maybe share ownership of the gem with that account? Otherwise we'll have to constantly be chasing you :)

**Comment by sergioisidoro** [comment]
@domaindrivendev Any updates on this?

**Comment by PedroSeda** [comment]
@BookOfGreg @sergioisidoro @domaindrivendev 
I'm more than happy to help if you need an extra pair of hands to maintain.
We have an Rails 7 application using rswag, and it's working wonders so far.

**Comment by domaindrivendev** [comment]
@BookOfGreg just gave you ownership perms for the `rswag`, `rswag-api`, `rswag-specs` and `rswag-ui` gems. Let me know if you need anything else.

**Comment by BookOfGreg** [comment]
<img width="289" alt="image" src="https://user-images.githubusercontent.com/637868/153090715-674b8704-3b11-4269-8af0-61885fcc848b.png">

🎉 🎉  We are BACK IN BUSINESS!  🎉 🎉 

Anyone who is an Rswag member can deploy safely without mine or DDD's involvement via GH Action. It's a little clunky for now (manually specify version) but that can be the subject of a new issue. At the current point in time there are 6 people who have the ability to deploy.

@sergioisidoro did you mention about starting a slack or discord or other method of chat?
@athix @PedroSeda @jtannas I'll grant the three of you Triage ability on this repo at this time as you expressed an interest in helping. 🙏 Thanks for bringing this to the front of our attention, in these strange times time passed strangely and I had lost track how long it had really been.

**Comment by lucymidgleyopi** [comment]
Hi @BookOfGreg I work with @jtannas  and would also be interested in helping out if you need any more hands!

**Comment by BookOfGreg** [comment]
Hi @lucymidgleyopi I checked with Joel and added in also.

For anyone else who chances on this thread. Feel free to add to the thread or make a new issue also. Either myself or Sergio should have permission over time, and hopefully over time grant others the ability to add new Triage and Write and other members to the org.
