### ISSUE TITLE
Rswag UI doesn't mounted well

### ISSUE THREAD

**Issue by coins-black** [rswag/rswag#469]
Hi!

When I try to setup new rails 7.0.0. with Rswag i give errors after visit browser (rails server started):

```
GET http://localhost:3000/api-docs/swagger-ui.css
[HTTP/1.1 404 Not Found 1055ms]

GET http://localhost:3000/api-docs/swagger-ui-bundle.js
[HTTP/1.1 404 Not Found 1046ms]

GET http://localhost:3000/api-docs/swagger-ui-standalone-preset.js
[HTTP/1.1 404 Not Found 1046ms]

GET http://localhost:3000/api-docs/swagger-ui-bundle.js
[HTTP/1.1 404 Not Found 138ms]

...
```
And so on...

How to solve this? Thanks!

**Comment by strifek** [comment]
A possible workaround for this issue is to use a CDN-provided assets. To achieve this you'll have to:
1. export customizable `index.html.erb` file by calling `rails g rswag:ui:custom` (it'll be placed in `views/rswag/ui/home`)
2. in exported file change those lines:
```
  <link rel="stylesheet" type="text/css" href="./swagger-ui.css" >
  <link rel="icon" type="image/png" href="./favicon-32x32.png" sizes="32x32" />
  <link rel="icon" type="image/png" href="./favicon-16x16.png" sizes="16x16" />
  ...
  <script src="./swagger-ui-bundle.js"> </script>
  <script src="./swagger-ui-standalone-preset.js"> </script>
```
  to:
```
  <link rel="stylesheet" type="text/css" href="https://unpkg.com/swagger-ui-dist@3.52.5/swagger-ui.css">
  <link rel="icon" type="image/png" href="https://unpkg.com/swagger-ui-dist@3.52.5/favicon-32x32.png" sizes="32x32" />
  <link rel="icon" type="image/png" href="https://unpkg.com/swagger-ui-dist@3.52.5/favicon-16x16.png" sizes="16x16" />
  ...
  <script src="https://unpkg.com/swagger-ui-dist@3.52.5/swagger-ui-bundle.js"></script>
  <script src="https://unpkg.com/swagger-ui-dist@3.52.5/swagger-ui-standalone-preset.js"> </script>
```

Hope this will be useful :)

**Comment by coins-black** [comment]
@strifek works like a charm!
Thanks!

**Comment by morgoth** [comment]
@BookOfGreg Are there any chances anytime soon for a stable release with Rails 7 support, to avoid such issues?

**Comment by marclennox** [comment]
I've also run into this problem on Rails 7.0.

**Comment by CarlosCD** [comment]
I see this same problem, using master (cb87c5aeff42f4b47b9963b85ddba47cb41780d1) with Rails 6.1.4.

**Comment by BookOfGreg** [comment]
@CarlosCD can you try on version 2.5.1 and let me know if that works? It should have been fixed as this looks like a dup of #467

**Comment by CarlosCD** [comment]
Yes, 2.5.1 works. That has been my fallback.

One of our developers was pulling master in preparation for Rails 7, that is what made me aware of the issue.

**Comment by BookOfGreg** [comment]
Yep, sorry about that, we transferred from TravisCI to GitHub and it's hard to know deployment related things in advance and a small mistake crept in. Glad this is sorted for you and all others in the thread.

If anyone has related problems to missing please comment or open a new issue.

**Comment by rstueven** [comment]
~~Maybe it's way too late to mention here, but I'm having the same problem:~~
~~rswag 2.8.0~~
~~Rails 7.0.4~~
~~Ruby 3.1.3~~

~~Trying @strifek's suggestion of getting the files from CDN results in a bunch of Content Security Policy errors.~~

~~I've also tried copying the files into my assets directory, but uglifier chokes on one of the JavaScript files.~~

Running `bundle exec rake rswag:ui:copy_assets\[public/api-docs\]` got the job done, just like the docs say. Sorry for the distraction.

Actually, two of the images are still denied because of CSP, but I can live without them.

`Refused to load the image 'https://validator.swagger.io/validator?url=https%3A%2F%2Feval.scorevision.com%2Fapi-docs%2Findex.html' because it violates the following Content Security Policy directive: "img-src 'self' data:".`
`index.html:1 Refused to load the image 'https://validator.swagger.io/validator?url=https%3A%2F%2Feval.scorevision.com%2Fapi-docs%2Fv1%2Fswagger.yaml' because it violates the following Content Security Policy directive: "img-src 'self' data:".`

**Comment by elthariel** [comment]
Same problem on master with Rails 8.x
Fixed it by installing the `swagger-ui-dist`  node module and added this hack in rswag-ui config

```ruby
Rswag::Ui.configure do |c|
  # ...
  c.instance_variable_set(
    :@assets_root,
    Rails.root.join('node_modules/swagger-ui-dist')
  )
  # ...
end
```
