### ISSUE TITLE
This line creates a circular dependency

### ISSUE THREAD

**Issue by kwstannard** [rswag/rswag#523]
Hi rswag team,

I ran into an error caused by the circular dependency while trying to extend swagger_formatter to add a leading comment to the swagger.yaml file.

https://github.com/rswag/rswag/blob/8a6ebbef9777ae2d81dfc13f950d41270ebe621f/rswag-specs/lib/rswag/specs/swagger_formatter.rb#L5

The app depends on rswag-specs, but swagger_helper lives in the app which means that rswag-specs depends on the app in turn, creating a circular dependency.

Regards,
Kelly

**Comment by gentaro-sakamoto** [comment]
@kwstannard how do you resolve this issue?

**Comment by jtannas** [comment]
@kwstannard thanks for the heads up.
I've been wrapped up with other issues for the past few months and am now getting back to this project. There's a lot to catch up on, but if you submit a PR I'll do my best to get it merged and released. Otherwise it might be awhile until I get to this :confused:

**Comment by kwstannard** [comment]
@gentaro-sakamoto Looks like I gave up :D 

I am also swamped, so idk if I will be opening a PR anytime soon.
