### ISSUE TITLE
[REQUEST] Is there a way to run specs in parallel on CI, and merge the results together?

### ISSUE THREAD

**Issue by ndbroadbent** [rswag/rswag#577]
## Is your feature request related to a problem? Please describe.

My rswag API tests are a bit slow, and I would like to run them in parallel on CI.

## Describe the solution you'd like

A command to "deep merge" partial swagger.json files together. Is this already possible?

**Comment by jtannas** [comment]
Hrmm... So this one is a bit of an interesting request... There's https://github.com/grosser/parallel_tests for running tests in parallel and it works fine in CI. If you're just looking to generate the swagger docs without running the tests there's `rake rswag:specs:swaggerize`. That tends to run pretty quickly since it doesn't actually run the tests.

Is that enough to help out with your use case?
