### ISSUE TITLE
[REQUEST] Can specific attributes be excluded from OpenApi yaml generation?

### ISSUE THREAD

**Issue by nikostitoworkable** [rswag/rswag#594]
## Is your feature request related to a problem? Please describe.
Too much noise from altered timestamps when generating swagger docs

## Describe the solution you'd like
Is there an option when running swaggerize rake task to exclude specific json response attributes from altering the yaml's original values?
I am interested in excluding attributes such as: `created_at`,`updated_at` that get altered every time we regenerate our docs, creating noise in our PRs and making merging so more difficult.

## What support could we give you, so you could implement this yourself?
Maybe add a flag to swaggerize rake task for excluding specific attribute names?

## Describe alternatives you've considered
None
## Additional context
None

## Relates to which version of OAS (OpenAPI Specification)
- [ ] OAS2
- [X] OAS3
- [ ] OAS3.1

Thanks for any inputs

**Comment by araccaine** [comment]
I circumvented it by patching `created_at` and `updated_at`:


`rswag` examples are only created when `RSWAG_DRY_RUN=0` is present in `ENV`. So I (ab)used this to add a "feature flag" that enforces unified timestamps:
 
```ruby
# config/environments/test.rb

Rails.application.configure do
  # Just an arbitrary config name
  # `config.x.some_setting` is just the rails convention for custom settings
  config.x.rswag.enforce_unified_example_timestamps = ENV['RSWAG_DRY_RUN'] == '0'
end
```

Then including a model concern in your models or directly in `ApplicationRecord` if you use rails 5 or higher:

```ruby
# app/models/concerns/rswag_unified_example_timestamps.rb

# Patches ActiveRecord's timestamps when running rswag together with example generation
module RswagUnifiedExampleTimestamps
  if Rails.configuration.x.rswag.enforce_unified_example_timestamps
    extend ActiveSupport::Concern

    # Some arbitrary fixed timestamp that should be used for all records.
    # Do not use `Time.new` here as this is not the correct format.
    UNIFIED_TIMESTAMP = Time.zone.parse('2025-01-01').freeze

    included do
      def created_at
        UNIFIED_TIMESTAMP
      end

      def updated_at
        UNIFIED_TIMESTAMP
      end
    end
  end
end
```

```ruby
# app/models/application_record.rb

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
 
  include RswagUnifiedExampleTimestamps
end
```

It does not feel right but I had no better idea.

**Note:**

Just be aware that any specs that are dependent on the timestamps may behave in a way you do not want/expect.

But since `$ rails rswag` does only run specs related to `rswag` you should be pretty safe here.
