### ISSUE TITLE
[SECURITY] Path traversal exposing arbitrary yml and json files in the application

### ISSUE THREAD

**Issue by carlobeltrame** [rswag/rswag#653]
I am reporting this security issue here as a public issue, as instructed in the SECURITY.md of this repo.
@BookOfGreg @oblakeerickson @romanblanco @sergioisidoro

## Describe the bug
On the latest version of rswag-api, the middleware [reads the path](https://github.com/rswag/rswag/blob/master/rswag-api/lib/rswag/api/middleware.rb#L15) of the requested URL, and if it is a .yml, .yaml or .json file [resolves this path against the swagger root](https://github.com/rswag/rswag/blob/master/rswag-api/lib/rswag/api/middleware.rb#L16) and [returns its contents](https://github.com/rswag/rswag/blob/master/rswag-api/lib/rswag/api/middleware.rb#L19..L28). Using a simple dot-dot-slash technique (and manually sending the http request instead of in a browser), this allows an attacker to read out any YAML or JSON files anywhere on the server. If rswag is used within a rails application, this includes config settings and secrets files.

## Steps to Test or Reproduce
I will not provide step-by-step reproduction instructions unless explicitly prompted to do so by the maintainers of this gem.

## Expected behavior
rswag-api should only ever expose the specific OpenAPI spec file(s) of the project. At the very least, the middleware should validate that the resolved path lies within the gem's directory. Better yet, it should only allow fetching explicitly allowlisted files. We already have to tell rswag-ui the name of the OpenAPI spec (using `.swagger_endpoint` inside a `Rswag::Ui.configure` initializer). The same information should also be used as an allowlist for rswag-api.

## Additional context
You should probably fix your issue templates. When trying to report a security vulnerability, the issue template selector just leads me to your SECURITY.md, which states to just open an issue.

## Dependency versions
The version of are you using for:
* Rswag: 2.8.0, but the bug is also present in the latest version 2.9.0
* RSpec: 3.10.0
* Rails: 6.1.7.1
* Ruby: 2.7

## Relates to which version of OAS (OpenAPI Specification)
- [ ] OAS2
- [ ] OAS3
- [ ] OAS3.1

**Comment by sergioisidoro** [comment]
Thank you so much for taking the time to investigate and reporting this. 

Because rswag ui and rswag api are different gems, I don't think we can easily proceed with the proposed solution without a breaking change. I propose the path sanitisation, and trying to get a patch release to get this fixed asap to as many people as possible.

Did you report a CVE? That's a good way to create a warning on security scanners to ensure as much people will update this. In my own assessment, this would classify as a high security vulnerability (the only mitigation being that only it only affects yaml and json files, which is not much of a mitigation given they are the most widespread config formats)

As to the fix, I'm thinking expanding the path, and then matching the root with swagger root and bailing out in case it does not match. But I did not validate this yet. Anyone else on the case?

```.rb
      def call(env)
        path = env['PATH_INFO']
        # Sanitize the filename for directory traversal by expanding, and amtching the swagger roor directory
        filename = File.expand_path(File.join(@config.resolve_swagger_root(env), path))
        unless filename.match Regexp.new('^' + Regexp.escape(@config.resolve_swagger_root(env))) do
          return @app.call(env)
        end
          ...
```

Drafted something here: https://github.com/rswag/rswag/pull/654

**Comment by carlobeltrame** [comment]
I have not yet created a CVE. I would agree that would be a good way to spread the word. I can create one if you would like me to (never done that before, but it can't be that hard).

**Comment by romanblanco** [comment]
@carlobeltrame, would you like to give it a try?

I have not created CVE myself either, but can try to ask around for someone with the expertise.

**Comment by carlobeltrame** [comment]
@romanblanco On Monday I requested a CVE at https://cveform.mitre.org/, as a security professional at my workplace advised. The request has been received and is currently being processed.
In the meantime, I see you have merged a fix for this issue, and published a GitHub release. However, I don't find the new release on rubygems yet. Would you be so kind to release it there as well? Otherwise I can't install the updated version.

**Comment by romanblanco** [comment]
@carlobeltrame Thank you, for working on the CVE!

And for pointing out that the release was not at rubygems, shoud be fixed now :+1:

**Comment by carlobeltrame** [comment]
@romanblanco thanks for the quick reaction! I just tested it out, and a bug has been introduced in the fix PR, which broke swagger file resolution altogether. See https://github.com/rswag/rswag/pull/654#discussion_r1262688116 for details and #660 for a fix.
I guess this breaking change means the 2.10 version is not a useable fixed version for the security issue, and you'll have to release a new (patch) release. Once you have done that, I will communicate to the CVE authority that the first working fixed version will be 2.10.1.

**Comment by romanblanco** [comment]
@carlobeltrame Thanks for creating the fixing PR!

**Comment by romanblanco** [comment]
https://rubygems.org/gems/rswag/versions/2.10.1

**Comment by gobijan** [comment]
You guys are quick. I just came here to report the 2.10 bug and you already fixed it <3

**Comment by gobijan** [comment]
Maybe the swagger.yaml file should be made explicitly accessible by the server via the rails routes and not made available via file parsing? This would minimize the attack surface area?

**Comment by carlobeltrame** [comment]
The problem is that rswag-api does not really have access to the same [config information](https://github.com/rswag/rswag#enable-swagger-endpoints-for-swagger-ui) set through `Rswag::Ui.configure` because it is a separate gem. So effectively, users would have to add the `Rswag::Ui` config and routes for the exact same configuration. This wouldn't be very DRY (as in, could be done better if we change things anyways), and at the same time would be a breaking change. That's why such options were dismissed in https://github.com/rswag/rswag/issues/653#issuecomment-1614985128

TLDR: The maintainers opted for the current fix because it is free of breaking changes and code duplication in userland code.

**Comment by gobijan** [comment]
Makes sense for the hotfix.

**Comment by romanblanco** [comment]
@carlobeltrame has there been a progress in communication with the CVE authority?

> @romanblanco thanks for the quick reaction! I just tested it out, and a bug has been introduced in the fix PR, which broke swagger file resolution altogether. See [#654 (comment)](https://github.com/rswag/rswag/pull/654#discussion_r1262688116) for details and #660 for a fix. I guess this breaking change means the 2.10 version is not a useable fixed version for the security issue, and you'll have to release a new (patch) release. Once you have done that, I will communicate to the CVE authority that the first working fixed version will be 2.10.1.

**Comment by carlobeltrame** [comment]
Yes, we got CVE-2023-38337

**Comment by carlobeltrame** [comment]
I think with that, we can close this issue, right? Problem is fixed (I verified it in my application), and the CVE is published and should trigger dependabot alerts.

Thanks to the maintainers for the quick and constructive reaction!

**Comment by eric-hemasystems** [comment]
Wanted to note I didn't get an alert about this for Github like I do for most projects. I think it is because I am loading rswag by component [per the instructions](https://github.com/rswag/rswag/blob/master/README.md?plain=1#L72-L81) so I don't actually have `rswag` itself in my Gemfile.

Since those instructions are one of the documented options I'm guessing I'm probably not the only one. Therefore for security updates it seems it would be best if the security update was tied to the subcomponent such as `rswag-api`. This way regardless of install method everyone gets a notice.

My guess is since [the advisory](https://github.com/advisories/GHSA-vc79-65pr-q82v) is already published changing it after-the-fact is probably not doable. Although perhaps we could still update the [ruby-advisory-db](https://github.com/rubysec/ruby-advisory-db/blob/master/gems/rswag/CVE-2023-38337.yml) which many tools such as [bundle-audit](https://github.com/rubysec/bundler-audit) feed off of (would that end up triggering extra alerts for folks though?)

Regardless of if anything can be done retroactively to this CVE I just wanted to post a note to suggest making future security alerts specific to the sub-component so everybody gets a notice since installing via sub-component is a documented supported way to set rswag up.

**Comment by francois-ferrandis** [comment]
Thank you @eric-hemasystems for your very informative comment. 

My team was in the same situation, and we stumbled upon this issue and CVE after being attacked today. The problem you describe is likely to be putting other projects at risk.

Is anyone here aware of a solution that would trigger a dependabot alert for the teams that use `rswag-api` directly (as per instructions)?

Thank you all for your time.

**Comment by carlobeltrame** [comment]
We could either amend the existing CVE or open a new one for rswag-api specifically. For the former option, I'm not sure what implications this would have on the various audit tooling out there.
