### ISSUE TITLE
Allow optional parameters in path

### ISSUE THREAD

**Issue by iagopiimenta** [rswag/rswag#98]
Currently all path parameters are required, see:

https://github.com/domaindrivendev/rswag/blob/d91601b02cf29262963e07db816e8cd54336e018/rswag-specs/lib/rswag/specs/example_group_helpers.rb#L40

rswag should consider the `required` parameter as well as the `in: body` considers

**Comment by domaindrivendev** [comment]
As per the Swagger 2.0 specification (implemented by rswag), path parameters MUST always be required - https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#parameter-object.

Specifically see the description for the `required` field:

_"Determines whether this parameter is mandatory. If the parameter is in "path", this property is required and its value MUST be true. Otherwise, the property MAY be included and its default value is false."_
